//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.Tests.Testing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AI_Prompts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AI_Prompts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.Tests.Testing.Resources.AI_Prompts", typeof(AI_Prompts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;Pre-translate prompt&quot;,
        ///  &quot;action&quot;: &quot;pre_translate&quot;,
        ///  &quot;aiProviderId&quot;: 1,
        ///  &quot;aiModelId&quot;: &quot;gpt-3.5-turbo-instruct&quot;,
        ///  &quot;config&quot;: {
        ///    &quot;mode&quot;: &quot;basic&quot;,
        ///    &quot;companyDescription&quot;: &quot;string&quot;,
        ///    &quot;projectDescription&quot;: &quot;string&quot;,
        ///    &quot;audienceDescription&quot;: &quot;string&quot;,
        ///    &quot;otherLanguageTranslations&quot;: {
        ///      &quot;isEnabled&quot;: true,
        ///      &quot;languageIds&quot;: [
        ///        &quot;uk&quot;
        ///      ]
        ///    },
        ///    &quot;glossaryTerms&quot;: true,
        ///    &quot;tmSuggestions&quot;: true,
        ///    &quot;fileContent&quot;: true,
        ///    &quot;fileContext&quot;: true,
        ///    &quot;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddAiPrompt_Request {
            get {
                return ResourceManager.GetString("AddAiPrompt_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;identifier&quot;: &quot;50fb3506-4127-4ba8-8296-f97dc7e3e0c3&quot;,
        ///    &quot;status&quot;: &quot;finished&quot;,
        ///    &quot;progress&quot;: 100,
        ///    &quot;attributes&quot;: {
        ///      &quot;aiPromptId&quot;: 38
        ///    },
        ///    &quot;createdAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;updatedAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;startedAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;finishedAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;eta&quot;: &quot;1 second&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string CommonResponses_AiPromptCompletion {
            get {
                return ResourceManager.GetString("CommonResponses_AiPromptCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [{
        ///    &quot;id&quot;: 2,
        ///    &quot;name&quot;: &quot;Pre-translate prompt&quot;,
        ///    &quot;action&quot;: &quot;pre_translate&quot;,
        ///    &quot;aiProviderId&quot;: 2,
        ///    &quot;aiModelId&quot;: &quot;gpt-3.5-turbo-instruct&quot;,
        ///    &quot;isEnabled&quot;: true,
        ///    &quot;enabledProjectIds&quot;: [
        ///      1
        ///    ],
        ///    &quot;config&quot;: {
        ///      &quot;mode&quot;: &quot;basic&quot;,
        ///      &quot;companyDescription&quot;: &quot;string&quot;,
        ///      &quot;projectDescription&quot;: &quot;string&quot;,
        ///      &quot;audienceDescription&quot;: &quot;string&quot;,
        ///      &quot;otherLanguageTranslations&quot;: {
        ///        &quot;isEnabled&quot;: true,
        ///        &quot;languageIds&quot;: [
        ///          &quot;uk&quot;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommonResponses_Multi {
            get {
                return ResourceManager.GetString("CommonResponses_Multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 2,
        ///    &quot;name&quot;: &quot;Pre-translate prompt&quot;,
        ///    &quot;action&quot;: &quot;pre_translate&quot;,
        ///    &quot;aiProviderId&quot;: 2,
        ///    &quot;aiModelId&quot;: &quot;gpt-3.5-turbo-instruct&quot;,
        ///    &quot;isEnabled&quot;: true,
        ///    &quot;enabledProjectIds&quot;: [
        ///      1
        ///    ],
        ///    &quot;config&quot;: {
        ///      &quot;mode&quot;: &quot;basic&quot;,
        ///      &quot;companyDescription&quot;: &quot;string&quot;,
        ///      &quot;projectDescription&quot;: &quot;string&quot;,
        ///      &quot;audienceDescription&quot;: &quot;string&quot;,
        ///      &quot;otherLanguageTranslations&quot;: {
        ///        &quot;isEnabled&quot;: true,
        ///        &quot;languageIds&quot;: [
        ///          &quot;uk&quot;
        ///        ] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommonResponses_Single {
            get {
                return ResourceManager.GetString("CommonResponses_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;url&quot;: &quot;https://test.com&quot;,
        ///    &quot;expireIn&quot;: &quot;2019-09-20T10:31:21+00:00&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string DownloadAiPromptCompletion_Response {
            get {
                return ResourceManager.GetString("DownloadAiPromptCompletion_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///
        ///    &quot;path&quot;: &quot;/name&quot;,
        ///    &quot;op&quot;: &quot;replace&quot;,
        ///
        ///    &quot;value&quot;: &quot;new name&quot;
        ///  },
        ///
        ///  {
        ///
        ///    &quot;path&quot;: &quot;/aiProviderId&quot;,
        ///
        ///    &quot;op&quot;: &quot;replace&quot;,
        ///
        ///    &quot;value&quot;: 1
        ///
        ///  }
        ///].
        /// </summary>
        internal static string EditAiPrompt_Request {
            get {
                return ResourceManager.GetString("EditAiPrompt_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;resources&quot;: {
        ///    &quot;projectId&quot;: 1,
        ///    &quot;targetLanguageId&quot;: &quot;uk&quot;,
        ///    &quot;stringIds&quot;: [
        ///      1, 2, 3
        ///    ]
        ///  },
        ///  &quot;tools&quot;: [
        ///    {
        ///      &quot;tool&quot;: {
        ///        &quot;type&quot;: &quot;function&quot;,
        ///        &quot;function&quot;: {
        ///          &quot;name&quot;: &quot;func&quot;,
        ///          &quot;description&quot;: &quot;func desc&quot;
        ///        }
        ///      }
        ///    }
        ///  ],
        ///  &quot;tool_choice&quot;: &quot;string&quot;
        ///}.
        /// </summary>
        internal static string GenerateAiPromptCompletion_Request {
            get {
                return ResourceManager.GetString("GenerateAiPromptCompletion_Request", resourceCulture);
            }
        }
    }
}
