//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.Tests.Testing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Applications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Applications() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.Tests.Testing.Resources.Applications", typeof(Applications).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;path&quot;: &quot;/permissions&quot;,
        ///    &quot;op&quot;: &quot;replace&quot;,
        ///    &quot;value&quot;: {
        ///      &quot;user&quot;: {
        ///        &quot;value&quot;: &quot;restricted&quot;,
        ///        &quot;ids&quot;: [
        ///          1
        ///        ]
        ///      },
        ///      &quot;project&quot;: {
        ///        &quot;value&quot;: &quot;restricted&quot;,
        ///        &quot;ids&quot;: [
        ///          1
        ///        ]
        ///      }
        ///    }
        ///  }
        ///].
        /// </summary>
        internal static string EditInstallation_Request {
            get {
                return ResourceManager.GetString("EditInstallation_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            {
        ///                &quot;data&quot;: {
        ///                  &quot;identifier&quot;: &quot;some_application&quot;,
        ///                  &quot;name&quot;: &quot;Video Preview&quot;,
        ///                  &quot;logo&quot;: &quot;/logo.png&quot;,
        ///                  &quot;baseUrl&quot;: &quot;https://video-preview.awesome-crowdin.com&quot;,
        ///                  &quot;scopes&quot;: [
        ///                    &quot;project&quot;
        ///                  ]
        ///                }
        ///            }
        ///        .
        /// </summary>
        internal static string GetApplicationData_Response {
            get {
                return ResourceManager.GetString("GetApplicationData_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;identifier&quot;: &quot;test-application&quot;,
        ///    &quot;name&quot;: &quot;Test Application&quot;,
        ///    &quot;description&quot;: &quot;Test Description&quot;,
        ///    &quot;logo&quot;: &quot;/logo.png&quot;,
        ///    &quot;baseUrl&quot;: &quot;https://localhost.dev&quot;,
        ///    &quot;manifestUrl&quot;: &quot;https://localhost.dev&quot;,
        ///    &quot;createdAt&quot;: &quot;2024-01-13T11:34:40+00:00&quot;,
        ///    &quot;modules&quot;: [
        ///      {
        ///        &quot;key&quot;: &quot;test-application&quot;,
        ///        &quot;type&quot;: &quot;module-type&quot;,
        ///        &quot;data&quot;: {},
        ///        &quot;authenticationType&quot;: &quot;none&quot;
        ///      }
        ///    ],
        ///    &quot;scopes&quot;: [
        ///      &quot;project&quot;
        ///    ],
        ///    &quot;permiss [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetApplicationInstallation_Response {
            get {
                return ResourceManager.GetString("GetApplicationInstallation_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [
        ///   {
        ///  &quot;data&quot;: {
        ///    &quot;identifier&quot;: &quot;test-application&quot;,
        ///    &quot;name&quot;: &quot;Test Application&quot;,
        ///    &quot;description&quot;: &quot;Test Description&quot;,
        ///    &quot;logo&quot;: &quot;/logo.png&quot;,
        ///    &quot;baseUrl&quot;: &quot;https://localhost.dev&quot;,
        ///    &quot;manifestUrl&quot;: &quot;https://localhost.dev&quot;,
        ///    &quot;createdAt&quot;: &quot;2024-01-13T11:34:40+00:00&quot;,
        ///    &quot;modules&quot;: [
        ///      {
        ///        &quot;key&quot;: &quot;test-application&quot;,
        ///        &quot;type&quot;: &quot;module-type&quot;,
        ///        &quot;data&quot;: {},
        ///        &quot;authenticationType&quot;: &quot;none&quot;
        ///      }
        ///    ],
        ///    &quot;scopes&quot;: [
        ///      &quot;project&quot;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListApplicationInstallation_Response {
            get {
                return ResourceManager.GetString("ListApplicationInstallation_Response", resourceCulture);
            }
        }
    }
}
