//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.Tests.Testing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Branches {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Branches() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.Tests.Testing.Resources.Branches", typeof(Branches).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;develop-master&quot;,
        ///  &quot;title&quot;: &quot;Master branch&quot;
        ///}.
        /// </summary>
        internal static string Request_AddBranch {
            get {
                return ResourceManager.GetString("Request_AddBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;develop-master&quot;,
        ///  &quot;title&quot;: &quot;Master branch&quot;
        ///}.
        /// </summary>
        internal static string Request_CloneBranch {
            get {
                return ResourceManager.GetString("Request_CloneBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;path&quot;: &quot;/name&quot;,
        ///        &quot;op&quot;: &quot;replace&quot;,
        ///        &quot;value&quot;: &quot;develop-master&quot;
        ///    },
        ///    {
        ///        &quot;path&quot;: &quot;/title&quot;,
        ///        &quot;op&quot;: &quot;replace&quot;,
        ///        &quot;value&quot;: &quot;Master branch&quot;
        ///    }
        ///].
        /// </summary>
        internal static string Request_EditBranch {
            get {
                return ResourceManager.GetString("Request_EditBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;deleteAfterMerge&quot;: true,
        ///  &quot;sourceBranchId&quot;: 8,
        ///  &quot;dryRun&quot;: true
        ///}.
        /// </summary>
        internal static string Request_MergeBranch {
            get {
                return ResourceManager.GetString("Request_MergeBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;identifier&quot;: &quot;50fb3506-4127-4ba8-8296-f97dc7e3e0c3&quot;,
        ///    &quot;status&quot;: &quot;finished&quot;,
        ///    &quot;progress&quot;: 100,
        ///    &quot;attributes&quot;: {},
        ///    &quot;createdAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;updatedAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;startedAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;finishedAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string Response_BranchCloneStatus {
            get {
                return ResourceManager.GetString("Response_BranchCloneStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;identifier&quot;: &quot;50fb3506-4127-4ba8-8296-f97dc7e3e0c3&quot;,
        ///    &quot;status&quot;: &quot;finished&quot;,
        ///    &quot;progress&quot;: 100,
        ///    &quot;attributes&quot;: {
        ///      &quot;sourceBranchId&quot;: 38,
        ///      &quot;deleteAfterMerge&quot;: false
        ///    },
        ///    &quot;createdAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;updatedAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;startedAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;finishedAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string Response_BranchMergeStatus {
            get {
                return ResourceManager.GetString("Response_BranchMergeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;status&quot;: &quot;merged&quot;,
        ///    &quot;sourceBranchId&quot;: 100,
        ///    &quot;targetBranchId&quot;: 100,
        ///    &quot;dryRun&quot;: false,
        ///    &quot;details&quot;: {
        ///      &quot;added&quot;: 1,
        ///      &quot;deleted&quot;: 2,
        ///      &quot;updated&quot;: 3,
        ///      &quot;conflicted&quot;: 7
        ///    }
        ///  }
        ///}.
        /// </summary>
        internal static string Response_BranchMergeSummary {
            get {
                return ResourceManager.GetString("Response_BranchMergeSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;data&quot;: {
        ///        &quot;id&quot;: 34,
        ///        &quot;projectId&quot;: 2,
        ///        &quot;name&quot;: &quot;develop-master&quot;,
        ///        &quot;title&quot;: &quot;Master branch&quot;,
        ///        &quot;createdAt&quot;: &quot;2019-09-16T13:48:04+00:00&quot;,
        ///        &quot;updatedAt&quot;: &quot;2019-09-19T13:25:27+00:00&quot;
        ///      }
        ///    }
        ///  ],
        ///  &quot;pagination&quot;: {
        ///    &quot;offset&quot;: 0,
        ///    &quot;limit&quot;: 25
        ///  }
        ///}.
        /// </summary>
        internal static string Response_Common_Multi {
            get {
                return ResourceManager.GetString("Response_Common_Multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 34,
        ///    &quot;projectId&quot;: 2,
        ///    &quot;name&quot;: &quot;develop-master&quot;,
        ///    &quot;title&quot;: &quot;Master branch&quot;,
        ///    &quot;createdAt&quot;: &quot;2019-09-16T13:48:04+00:00&quot;,
        ///    &quot;updatedAt&quot;: &quot;2019-09-19T13:25:27+00:00&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string Response_Common_Single {
            get {
                return ResourceManager.GetString("Response_Common_Single", resourceCulture);
            }
        }
    }
}
