//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.Tests.Testing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Core_BugCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Core_BugCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.Tests.Testing.Resources.Core_BugCases", typeof(Core_BugCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 4,
        ///    &quot;name&quot;: &quot;Proofread&quot;,
        ///    &quot;url&quot;: &quot;https://webhook.site/1c20d9b5-6e6a-4522-974d-9da7ea7595c9&quot;,
        ///    &quot;events&quot;: [
        ///      &quot;project.created&quot;
        ///    ],
        ///    &quot;headers&quot;: [],
        ///    &quot;payload&quot;: {
        ///      &quot;project.created&quot;: {
        ///        &quot;event&quot;: &quot;{{event}}&quot;,
        ///        &quot;project&quot;: {
        ///          &quot;id&quot;: &quot;{{projectId}}&quot;,
        ///          &quot;userId&quot;: &quot;{{projectUserId}}&quot;,
        ///          &quot;sourceLanguageId&quot;: &quot;{{projectSourceLanguageId}}&quot;,
        ///          &quot;targetLanguageIds&quot;: &quot;{{projectTargetLanguageIds}}&quot;,
        ///          &quot;i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Response_OrgWebhook_HeadersArray {
            get {
                return ResourceManager.GetString("Response_OrgWebhook_HeadersArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 8,
        ///    &quot;type&quot;: 0,
        ///    &quot;userId&quot;: 6,
        ///    &quot;sourceLanguageId&quot;: &quot;en&quot;,
        ///    &quot;targetLanguageIds&quot;: [
        ///      &quot;es&quot;
        ///    ],
        ///    &quot;languageAccessPolicy&quot;: &quot;moderate&quot;,
        ///    &quot;name&quot;: &quot;Knowledge Base&quot;,
        ///    &quot;cname&quot;: &quot;my-custom-domain.crowdin.com&quot;,
        ///    &quot;identifier&quot;: &quot;1f198a4e907688bc65834a6d5a6000c3&quot;,
        ///    &quot;description&quot;: &quot;Vault of all terms and their explanation&quot;,
        ///    &quot;visibility&quot;: &quot;private&quot;,
        ///    &quot;logo&quot;: &quot;data:image/png;&quot;,
        ///    &quot;publicDownloads&quot;: true,
        ///    &quot;createdAt&quot;: &quot;2019-09-20T11:34:40+00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Response_ProjectSettings_TmPenalties {
            get {
                return ResourceManager.GetString("Response_ProjectSettings_TmPenalties", resourceCulture);
            }
        }
    }
}
