//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.Tests.Testing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Fields {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Fields() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.Tests.Testing.Resources.Fields", typeof(Fields).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            {
        ///                &quot;data&quot;: {
        ///                  &quot;id&quot;: 3,
        ///                  &quot;name&quot;: &quot;Client Corp&quot;,
        ///                  &quot;slug&quot;: &quot;Client Corp&quot;,
        ///                  &quot;type&quot;: &quot;select&quot;,
        ///                  &quot;description&quot;: &quot;Client corp field is appointed to store info about client corp&quot;,
        ///                  &quot;entities&quot;: [
        ///                    &quot;task&quot;
        ///                  ],
        ///                  &quot;config&quot;: {
        ///                    &quot;options&quot;: [
        ///                      {
        ///                        &quot;label&quot;: &quot;str&quot;,
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddAndGetField_Response {
            get {
                return ResourceManager.GetString("AddAndGetField_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            {
        ///              &quot;name&quot;: &quot;Client Corp&quot;,
        ///              &quot;slug&quot;: &quot;Client Corp&quot;,
        ///              &quot;type&quot;: &quot;select&quot;,
        ///              &quot;description&quot;: &quot;Client corp field is appointed to store info about client corp&quot;,
        ///              &quot;entities&quot;: [
        ///                &quot;task&quot;
        ///              ],
        ///              &quot;config&quot;: {
        ///                &quot;options&quot;: [
        ///                  {
        ///                    &quot;label&quot;: &quot;str&quot;,
        ///                    &quot;value&quot;: &quot;str&quot;
        ///                  }
        ///                ],
        ///                &quot;locations&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddField_Request {
            get {
                return ResourceManager.GetString("AddField_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            [
        ///                {
        ///                    &quot;path&quot;: &quot;/name&quot;,
        ///                    &quot;op&quot;: &quot;replace&quot;,
        ///                    &quot;value&quot;: &quot;UpdateClientCompanyName&quot;
        ///                },
        ///                {
        ///                    &quot;path&quot;: &quot;/config&quot;,
        ///                    &quot;op&quot;: &quot;replace&quot;,
        ///                    &quot;value&quot;: {
        ///                        &quot;options&quot;: [
        ///                            {
        ///                                &quot;label&quot;: &quot;UpdatedLabel&quot;,
        ///                                &quot;value&quot;: &quot;UpdatedValue&quot;
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EditField_Request {
            get {
                return ResourceManager.GetString("EditField_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            {
        ///                &quot;data&quot;: {
        ///                  &quot;id&quot;: 2,
        ///                  &quot;name&quot;: &quot;UpdateClientCompanyName&quot;,
        ///                  &quot;slug&quot;: &quot;Client Corp&quot;,
        ///                  &quot;type&quot;: &quot;select&quot;,
        ///                  &quot;description&quot;: &quot;Client corp field is appointed to store info about client corp&quot;,
        ///                  &quot;entities&quot;: [
        ///                    &quot;project&quot;,
        ///                    &quot;task&quot;
        ///                  ],
        ///                  &quot;config&quot;: {
        ///                    &quot;options&quot;: [
        ///                      {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EditField_Response {
            get {
                return ResourceManager.GetString("EditField_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            {
        ///                &quot;data&quot;: [
        ///                    {
        ///                        &quot;data&quot;: {
        ///                            &quot;id&quot;: 1,
        ///                            &quot;name&quot;: &quot;Custom field&quot;,
        ///                            &quot;slug&quot;: &quot;custom-field&quot;,
        ///                            &quot;description&quot;: &quot;Custom field description&quot;,
        ///                            &quot;type&quot;: &quot;select&quot;,
        ///                             &quot;config&quot;: {
        ///                                &quot;options&quot;: [
        ///                                    {
        ///                     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListFields_Response {
            get {
                return ResourceManager.GetString("ListFields_Response", resourceCulture);
            }
        }
    }
}
