//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.Tests.Testing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MachineTranslationEngines {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MachineTranslationEngines() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.Tests.Testing.Resources.MachineTranslationEngines", typeof(MachineTranslationEngines).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;engine name&quot;,
        ///  &quot;type&quot;: &quot;google_automl&quot;,
        ///  &quot;credentials&quot;: {
        ///    &quot;credentials&quot;: &quot;auto ml credentials&quot;
        ///  },
        ///  &quot;groupId&quot;: 2,
        ///  &quot;isEnabled&quot;: false
        ///}.
        /// </summary>
        internal static string AddMt_Request {
            get {
                return ResourceManager.GetString("AddMt_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 2,
        ///    &quot;groupId&quot;: 2,
        ///    &quot;name&quot;: &quot;Crowdin Translate&quot;,
        ///    &quot;type&quot;: &quot;crowdin&quot;,
        ///    &quot;credentials&quot;: {
        ///      &quot;crowdin_nmt&quot;: 1,
        ///      &quot;crowdin_nmt_multi_translations&quot;: 1
        ///    },
        ///    &quot;projectIds&quot;: [
        ///      1
        ///    ]
        ///  }
        ///}.
        /// </summary>
        internal static string AddMt_Response {
            get {
                return ResourceManager.GetString("AddMt_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;path&quot;: &quot;/name&quot;,
        ///
        ///    &quot;op&quot;: &quot;replace&quot;,
        ///
        ///    &quot;value&quot;: &quot;new engine name&quot;
        ///  },
        ///
        ///  {
        ///
        ///    &quot;path&quot;: &quot;/type&quot;,
        ///
        ///    &quot;op&quot;: &quot;replace&quot;,
        ///
        ///    &quot;value&quot;: &quot;custom_mt&quot;
        ///
        ///   }
        ///].
        /// </summary>
        internal static string EditMt_Request {
            get {
                return ResourceManager.GetString("EditMt_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;data&quot;: {
        ///        &quot;id&quot;: 2,
        ///        &quot;name&quot;: &quot;Crowdin Translate&quot;,
        ///        &quot;type&quot;: &quot;crowdin&quot;,
        ///        &quot;credentials&quot;: {
        ///          &quot;crowdin_nmt&quot;: 1,
        ///          &quot;crowdin_nmt_multi_translations&quot;: 2
        ///        },
        ///        &quot;supportedLanguageIds&quot;: [
        ///          &quot;en&quot;,
        ///          &quot;es&quot;,
        ///          &quot;pl&quot;,
        ///          &quot;de&quot;,
        ///          &quot;fr&quot;,
        ///          &quot;zh-CN&quot;,
        ///          &quot;ja&quot;
        ///        ],
        ///        &quot;supportedLanguagePairs&quot;: {
        ///          &quot;en&quot;: [
        ///            &quot;de&quot;,
        ///            &quot;fr&quot;
        ///          ],        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListMts_Request_IntCredentialsKey {
            get {
                return ResourceManager.GetString("ListMts_Request_IntCredentialsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;data&quot;: {
        ///        &quot;id&quot;: 2,
        ///        &quot;name&quot;: &quot;Crowdin Translate&quot;,
        ///        &quot;type&quot;: &quot;crowdin&quot;,
        ///        &quot;credentials&quot;: {
        ///          &quot;crowdin_nmt&quot;: &quot;stringValue&quot;,
        ///          &quot;crowdin_nmt_multi_translations&quot;: &quot;stringValue&quot;
        ///        },
        ///        &quot;supportedLanguageIds&quot;: [
        ///          &quot;en&quot;,
        ///          &quot;es&quot;,
        ///          &quot;pl&quot;,
        ///          &quot;de&quot;,
        ///          &quot;fr&quot;,
        ///          &quot;zh-CN&quot;,
        ///          &quot;ja&quot;
        ///        ],
        ///        &quot;supportedLanguagePairs&quot;: {
        ///          &quot;en&quot;: [
        ///            &quot;de&quot;,
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListMts_Request_StringCredentialsKey {
            get {
                return ResourceManager.GetString("ListMts_Request_StringCredentialsKey", resourceCulture);
            }
        }
    }
}
