//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.Tests.Testing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Reports {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reports() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.Tests.Testing.Resources.Reports", typeof(Reports).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;identifier&quot;: &quot;50fb3506-4127-4ba8-8296-f97dc7e3e0c3&quot;,
        ///    &quot;status&quot;: &quot;finished&quot;,
        ///    &quot;progress&quot;: 100,
        ///    &quot;attributes&quot;: {
        ///      &quot;format&quot;: &quot;xlsx&quot;,
        ///      &quot;reportName&quot;: &quot;costs-estimation&quot;,
        ///      &quot;schema&quot;: {}
        ///    },
        ///    &quot;createdAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;updatedAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;startedAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;finishedAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string CommonResponses_ReportStatus {
            get {
                return ResourceManager.GetString("CommonResponses_ReportStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;name&quot;: &quot;costs-estimation-pe&quot;,
        ///    &quot;schema&quot;: {
        ///      &quot;baseRates&quot;: {
        ///        &quot;fullTranslation&quot;: 0.1,
        ///        &quot;proofread&quot;: 0.12
        ///      },
        ///      &quot;individualRates&quot;: [
        ///        {
        ///          &quot;languageIds&quot;: [
        ///            &quot;uk&quot;, &quot;es&quot;
        ///          ],
        ///          &quot;userIds&quot;: [
        ///            1, 2, 3
        ///          ],
        ///          &quot;fullTranslation&quot;: 0.1,
        ///          &quot;proofread&quot;: 0.12
        ///        }
        ///      ],
        ///      &quot;netRateSchemes&quot;: {
        ///        &quot;tmMatch&quot;: [
        ///          {
        ///            &quot;matchType&quot;: &quot;100&quot;,
        ///            &quot;price&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CostEstimationPostEditing_ByTaskSchema_Request {
            get {
                return ResourceManager.GetString("CostEstimationPostEditing_ByTaskSchema_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;name&quot;: &quot;costs-estimation-pe&quot;,
        ///    &quot;schema&quot;: {
        ///      &quot;baseRates&quot;: {
        ///        &quot;fullTranslation&quot;: 0.1,
        ///        &quot;proofread&quot;: 0.12
        ///      },
        ///      &quot;individualRates&quot;: [
        ///        {
        ///          &quot;languageIds&quot;: [
        ///            &quot;uk&quot;, &quot;es&quot;
        ///          ],
        ///          &quot;userIds&quot;: [
        ///            1, 2, 3
        ///          ],
        ///          &quot;fullTranslation&quot;: 0.1,
        ///          &quot;proofread&quot;: 0.12
        ///        }
        ///      ],
        ///      &quot;netRateSchemes&quot;: {
        ///        &quot;tmMatch&quot;: [
        ///          {
        ///            &quot;matchType&quot;: &quot;100&quot;,
        ///            &quot;price&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CostEstimationPostEditing_GeneralSchema_Request {
            get {
                return ResourceManager.GetString("CostEstimationPostEditing_GeneralSchema_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;name&quot;:&quot;costs-estimation&quot;,&quot;schema&quot;:{&quot;mode&quot;:&quot;simple&quot;,&quot;currency&quot;:&quot;UAH&quot;}}.
        /// </summary>
        internal static string GenerateReport_Request {
            get {
                return ResourceManager.GetString("GenerateReport_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;group-translation-costs-pe&quot;,
        ///  &quot;schema&quot;: {
        ///    &quot;projectIds&quot;: [
        ///      13
        ///    ],
        ///    &quot;unit&quot;: &quot;words&quot;,
        ///    &quot;currency&quot;: &quot;USD&quot;,
        ///    &quot;format&quot;: &quot;xlsx&quot;,
        ///    &quot;baseRates&quot;: {
        ///      &quot;fullTranslation&quot;: 0.1,
        ///      &quot;proofread&quot;: 0.12
        ///    },
        ///    &quot;individualRates&quot;: [
        ///      {
        ///        &quot;languageIds&quot;: [
        ///          &quot;uk&quot;
        ///        ],
        ///        &quot;userIds&quot;: [
        ///          1
        ///        ],
        ///        &quot;fullTranslation&quot;: 0.1,
        ///        &quot;proofread&quot;: 0.12
        ///      }
        ///    ],
        ///    &quot;netRateSchemes&quot;: {
        ///      &quot;tmMatch&quot;: [
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Group_TranslationCostsPostEditing_GeneralSchema_Request {
            get {
                return ResourceManager.GetString("Group_TranslationCostsPostEditing_GeneralSchema_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;pre-translate-efficiency&quot;,
        ///  &quot;schema&quot;: {
        ///    &quot;taskId&quot;: 1,
        ///    &quot;unit&quot;: &quot;strings&quot;,
        ///    &quot;format&quot;: &quot;xlsx&quot;,
        ///    &quot;postEditingCategories&quot;: [
        ///      &quot;0-10&quot;
        ///    ]
        ///  }
        ///}.
        /// </summary>
        internal static string PreTranslateEfficiency_ByTask_Request {
            get {
                return ResourceManager.GetString("PreTranslateEfficiency_ByTask_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;pre-translate-efficiency&quot;,
        ///  &quot;schema&quot;: {
        ///    &quot;languageId&quot;: &quot;ach&quot;,
        ///    &quot;dateFrom&quot;: &quot;2019-09-23T07:00:14+00:00&quot;,
        ///    &quot;dateTo&quot;: &quot;2019-09-27T07:00:14+00:00&quot;,
        ///    &quot;unit&quot;: &quot;strings&quot;,
        ///    &quot;format&quot;: &quot;xlsx&quot;,
        ///    &quot;postEditingCategories&quot;: [
        ///      &quot;0-10&quot;
        ///    ]
        ///  }
        ///}.
        /// </summary>
        internal static string PreTranslateEfficiency_General_Request {
            get {
                return ResourceManager.GetString("PreTranslateEfficiency_General_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;translation-costs-pe&quot;,
        ///  &quot;schema&quot;: {
        ///
        ///    &quot;taskId&quot;: 1,
        ///    &quot;unit&quot;: &quot;words&quot;,
        ///    &quot;currency&quot;: &quot;USD&quot;,
        ///    &quot;format&quot;: &quot;xlsx&quot;,
        ///    &quot;baseRates&quot;: {
        ///      &quot;fullTranslation&quot;: 0.1,
        ///      &quot;proofread&quot;: 0.12
        ///    },
        ///    &quot;individualRates&quot;: [
        ///      {
        ///        &quot;languageIds&quot;: [
        ///          &quot;uk&quot;
        ///        ],
        ///        &quot;userIds&quot;: [
        ///          1
        ///        ],
        ///        &quot;fullTranslation&quot;: 0.1,
        ///        &quot;proofread&quot;: 0.12
        ///      }
        ///    ],
        ///    &quot;netRateSchemes&quot;: {
        ///      &quot;tmMatch&quot;: [
        ///        {
        ///          &quot;matchT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TranslationCostsPostEditing_ByTaskSchema_Request {
            get {
                return ResourceManager.GetString("TranslationCostsPostEditing_ByTaskSchema_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;translation-costs-pe&quot;,
        ///  &quot;schema&quot;: {
        ///
        ///   &quot;groupBy&quot;: &quot;user&quot;,
        ///    &quot;languageId&quot;: &quot;ach&quot;,
        ///    &quot;userIds&quot;: [
        ///      13
        ///    ],
        ///    &quot;fileIds&quot;: [
        ///      138
        ///    ],
        ///    &quot;directoryIds&quot;: [
        ///      11
        ///    ],
        ///    &quot;branchIds&quot;: [
        ///      18
        ///    ],
        ///    &quot;unit&quot;: &quot;words&quot;,
        ///    &quot;currency&quot;: &quot;USD&quot;,
        ///    &quot;format&quot;: &quot;xlsx&quot;,
        ///    &quot;baseRates&quot;: {
        ///      &quot;fullTranslation&quot;: 0.1,
        ///      &quot;proofread&quot;: 0.12
        ///    },
        ///    &quot;individualRates&quot;: [
        ///      {
        ///        &quot;languageIds&quot;: [
        ///          &quot;uk&quot;
        ///        ],
        ///        &quot;userI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TranslationCostsPostEditing_GeneralSchema_Request {
            get {
                return ResourceManager.GetString("TranslationCostsPostEditing_GeneralSchema_Request", resourceCulture);
            }
        }
    }
}
