//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.Tests.Core.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AI_FineTuningDatasets {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AI_FineTuningDatasets() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Crowdin.Api.Tests.Core.Resources.AI_FineTuningDatasets", typeof(AI_FineTuningDatasets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string GenerateAiPromptFineTuningDataset_Request {
            get {
                return ResourceManager.GetString("GenerateAiPromptFineTuningDataset_Request", resourceCulture);
            }
        }
        
        internal static string CommonResponses_AiFineTuningDataset {
            get {
                return ResourceManager.GetString("CommonResponses_AiFineTuningDataset", resourceCulture);
            }
        }
        
        internal static string CreateAiPromptFineTuningJob_Request {
            get {
                return ResourceManager.GetString("CreateAiPromptFineTuningJob_Request", resourceCulture);
            }
        }
        
        internal static string CommonResponses_AiFineTuningJob {
            get {
                return ResourceManager.GetString("CommonResponses_AiFineTuningJob", resourceCulture);
            }
        }
        
        internal static string CommonResponses_DownloadLink {
            get {
                return ResourceManager.GetString("CommonResponses_DownloadLink", resourceCulture);
            }
        }
    }
}
