//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.Tests.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AI_Providers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AI_Providers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.Tests.Core.Resources.AI_Providers", typeof(AI_Providers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;OpenAI&quot;,
        ///  &quot;type&quot;: &quot;open_ai&quot;,
        ///  &quot;credentials&quot;: {
        ///    &quot;apiKey&quot;: &quot;string&quot;
        ///  },
        ///  &quot;config&quot;: {
        ///    &quot;actionRules&quot;: [
        ///      {
        ///        &quot;action&quot;: &quot;pre_translate&quot;,
        ///        &quot;availableAiModelIds&quot;: [
        ///          &quot;gpt-3.5-turbo-instruct&quot;
        ///        ]
        ///      }
        ///    ]
        ///  },
        ///  &quot;isEnabled&quot;: true,
        ///  &quot;useSystemCredentials&quot;: false
        ///}.
        /// </summary>
        internal static string AddAiProvider_Request {
            get {
                return ResourceManager.GetString("AddAiProvider_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;data&quot;: {
        ///        &quot;id&quot;: 2,
        ///        &quot;name&quot;: &quot;OpenAI&quot;,
        ///        &quot;type&quot;: &quot;open_ai&quot;,
        ///        &quot;credentials&quot;: {
        ///          &quot;apiKey&quot;: &quot;string&quot;
        ///        },
        ///        &quot;config&quot;: {
        ///          &quot;actionRules&quot;: [
        ///            {
        ///              &quot;action&quot;: &quot;pre_translate&quot;,
        ///              &quot;availableAiModelIds&quot;: [
        ///                &quot;gpt-3.5-turbo-instruct&quot;
        ///              ]
        ///            }
        ///          ]
        ///        },
        ///        &quot;isEnabled&quot;: true,
        ///        &quot;useSystemCredentials&quot;: false,
        ///        &quot;createdAt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommonResponses_Multi {
            get {
                return ResourceManager.GetString("CommonResponses_Multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 2,
        ///    &quot;name&quot;: &quot;OpenAI&quot;,
        ///    &quot;type&quot;: &quot;open_ai&quot;,
        ///    &quot;credentials&quot;: {
        ///      &quot;apiKey&quot;: &quot;string&quot;
        ///    },
        ///    &quot;config&quot;: {
        ///      &quot;actionRules&quot;: [
        ///        {
        ///          &quot;action&quot;: &quot;pre_translate&quot;,
        ///          &quot;availableAiModelIds&quot;: [
        ///            &quot;gpt-3.5-turbo-instruct&quot;
        ///          ]
        ///        }
        ///      ]
        ///    },
        ///    &quot;isEnabled&quot;: true,
        ///    &quot;useSystemCredentials&quot;: false,
        ///    &quot;createdAt&quot;: &quot;2019-09-20T11:11:05+00:00&quot;,
        ///    &quot;updatedAt&quot;: &quot;2019-09-20T12:22:20+00:00&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string CommonResponses_Single {
            get {
                return ResourceManager.GetString("CommonResponses_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///
        ///    &quot;path&quot;: &quot;/name&quot;,
        ///    &quot;op&quot;: &quot;replace&quot;,
        ///
        ///    &quot;value&quot;: &quot;OpenAI&quot;
        ///  },
        ///
        ///  {
        ///
        ///    &quot;path&quot;: &quot;/type&quot;,
        ///
        ///    &quot;op&quot;: &quot;replace&quot;,
        ///
        ///    &quot;value&quot;: &quot;open_ai&quot;
        ///
        ///  }
        ///].
        /// </summary>
        internal static string EditAiProvider_Request {
            get {
                return ResourceManager.GetString("EditAiProvider_Request", resourceCulture);
            }
        }
    }
}
