//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.Tests.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Bundles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Bundles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.Tests.Core.Resources.Bundles", typeof(Bundles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;Resx bundle&quot;,
        ///  &quot;format&quot;: &quot;crowdin-resx&quot;,
        ///  &quot;sourcePatterns&quot;: [
        ///    &quot;/master/&quot;
        ///  ],
        ///  &quot;ignorePatterns&quot;: [
        ///    &quot;/master/environments/&quot;
        ///  ],
        ///  &quot;exportPattern&quot;: &quot;strings-%two_letter_code%.resx&quot;,
        ///  &quot;isMultilingual&quot;: false,
        ///  &quot;includeProjectSourceLanguage&quot;: false,
        ///  &quot;labelIds&quot;: [
        ///    0
        ///  ]
        ///}.
        /// </summary>
        internal static string AddBundle_Request {
            get {
                return ResourceManager.GetString("AddBundle_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 1,
        ///    &quot;name&quot;: &quot;Resx bundle&quot;,
        ///    &quot;format&quot;: &quot;crowdin-resx&quot;,
        ///    &quot;sourcePatterns&quot;: [
        ///      &quot;/master/&quot;
        ///    ],
        ///    &quot;ignorePatterns&quot;: [
        ///      &quot;/master/environments/&quot;
        ///    ],
        ///    &quot;exportPattern&quot;: &quot;strings-%two_letters_code%.resx&quot;,
        ///    &quot;isMultilingual&quot;: false,
        ///    &quot;includeProjectSourceLanguage&quot;: false,
        ///    &quot;labelIds&quot;: [
        ///      0
        ///    ],
        ///    &quot;excludeLabelIds&quot;: [
        ///      1
        ///    ],
        ///    &quot;createdAt&quot;: &quot;2019-09-20T11:11:05+00:00&quot;,
        ///    &quot;updatedAt&quot;: &quot;2019-09-20T12:22:20+00:00&quot;
        ///  }
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommonResponses_Bundle {
            get {
                return ResourceManager.GetString("CommonResponses_Bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;identifier&quot;: &quot;50fb3506-4127-4ba8-8296-f97dc7e3e0c3&quot;,
        ///    &quot;status&quot;: &quot;finished&quot;,
        ///    &quot;progress&quot;: 100,
        ///    &quot;attributes&quot;: {
        ///        &quot;bundleId&quot;: 2
        ///    },
        ///    &quot;createdAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;updatedAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;startedAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;finishedAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;eta&quot;: &quot;1 second&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string CommonResponses_BundleExport {
            get {
                return ResourceManager.GetString("CommonResponses_BundleExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;url&quot;: &quot;https://production-enterprise-importer.downloads.crowdin.com/992000002/2/14.xliff?response-content-disposition=attachment%3B%20filename%3D%22APP.xliff%22&amp;X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&amp;X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Credential=AKIAIGJKLQV66ZXPMMEA%2F20190920%2Fus-east-1%2Fs3%2Faws4_request&amp;X-Amz-Date=20190920T093121Z&amp;X-Amz-SignedHeaders=host&amp;X-Amz-Expires=3600&amp;X-Amz-Signature=439ebd69a1b7e4c23e6d17891a491c94f832e0c82e4692dedb35a6cd1e624b62&quot;,
        ///    &quot;expireIn&quot;: &quot;2019- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DownloadBundle_Response {
            get {
                return ResourceManager.GetString("DownloadBundle_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;path&quot;: &quot;/name&quot;,
        ///    &quot;op&quot;: &quot;replace&quot;,
        ///
        ///    &quot;value&quot;: &quot;Resx bundle&quot;
        ///  },
        ///  {
        ///    &quot;path&quot;: &quot;/includeProjectSourceLanguage&quot;,
        ///    &quot;op&quot;: &quot;replace&quot;,
        ///    &quot;value&quot;: false
        ///  }
        ///].
        /// </summary>
        internal static string EditBundle_Request {
            get {
                return ResourceManager.GetString("EditBundle_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;data&quot;: {
        ///        &quot;id&quot;: 1,
        ///        &quot;projectId&quot;: 1,
        ///        &quot;name&quot;: &quot;develop-master&quot;,
        ///        &quot;title&quot;: &quot;Master branch&quot;,
        ///        &quot;createdAt&quot;: &quot;2019-09-16T13:48:04+00:00&quot;,
        ///        &quot;updatedAt&quot;: &quot;2019-09-19T13:25:27+00:00&quot;
        ///      }
        ///    }
        ///  ],
        ///  &quot;pagination&quot;: {
        ///    &quot;offset&quot;: 0,
        ///    &quot;limit&quot;: 25
        ///  }
        ///}.
        /// </summary>
        internal static string ListBundleBranches_Response {
            get {
                return ResourceManager.GetString("ListBundleBranches_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;data&quot;: {
        ///        &quot;id&quot;: 44,
        ///        &quot;projectId&quot;: 2,
        ///        &quot;branchId&quot;: 34,
        ///        &quot;directoryId&quot;: 4,
        ///        &quot;name&quot;: &quot;umbrella_app.xliff&quot;,
        ///        &quot;title&quot;: &quot;source_app_info&quot;,
        ///        &quot;type&quot;: &quot;xliff&quot;,
        ///        &quot;path&quot;: &quot;/directory1/directory2/filename.extension&quot;,
        ///        &quot;status&quot;: &quot;active&quot;,
        ///        &quot;revisionId&quot;: 1,
        ///        &quot;priority&quot;: &quot;normal&quot;,
        ///        &quot;importOptions&quot;: {
        ///          &quot;firstLineContainsHeader&quot;: false,
        ///          &quot;importTranslations&quot;: true,
        ///          &quot;sch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListBundleFiles_Response_AsProjectOwner {
            get {
                return ResourceManager.GetString("ListBundleFiles_Response_AsProjectOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;data&quot;: {
        ///        &quot;id&quot;: 44,
        ///        &quot;projectId&quot;: 2,
        ///        &quot;branchId&quot;: 34,
        ///        &quot;directoryId&quot;: 4,
        ///        &quot;name&quot;: &quot;umbrella_app.xliff&quot;,
        ///        &quot;title&quot;: &quot;source_app_info&quot;,
        ///        &quot;type&quot;: &quot;xliff&quot;,
        ///        &quot;path&quot;: &quot;/directory1/directory2/filename.extension&quot;,
        ///        &quot;status&quot;: &quot;active&quot;
        ///      }
        ///    }
        ///  ],
        ///  &quot;pagination&quot;: {
        ///    &quot;offset&quot;: 0,
        ///    &quot;limit&quot;: 25
        ///  }
        ///}.
        /// </summary>
        internal static string ListBundleFiles_Response_AsTranslator {
            get {
                return ResourceManager.GetString("ListBundleFiles_Response_AsTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;data&quot;: {
        ///        &quot;id&quot;: 1,
        ///        &quot;name&quot;: &quot;Resx bundle&quot;,
        ///        &quot;format&quot;: &quot;crowdin-resx&quot;,
        ///        &quot;sourcePatterns&quot;: [
        ///          &quot;/master/&quot;
        ///        ],
        ///        &quot;ignorePatterns&quot;: [
        ///          &quot;/master/environments/&quot;
        ///        ],
        ///        &quot;exportPattern&quot;: &quot;strings-%two_letters_code%.resx&quot;,
        ///        &quot;isMultilingual&quot;: false,
        ///        &quot;labelIds&quot;: [
        ///          0
        ///        ],
        ///        &quot;createdAt&quot;: &quot;2019-09-20T11:11:05+00:00&quot;,
        ///        &quot;updatedAt&quot;: &quot;2019-09-20T12:22:20+00:00&quot;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListBundles_Response {
            get {
                return ResourceManager.GetString("ListBundles_Response", resourceCulture);
            }
        }
    }
}
