//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.Tests.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Projects_StringsExporterSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Projects_StringsExporterSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.Tests.Core.Resources.Projects_StringsExporterSettings", typeof(Projects_StringsExporterSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            {
        ///                &quot;format&quot;: &quot;android&quot;,
        ///                &quot;settings&quot;: {
        ///                    &quot;convertPlaceHolders&quot;: true
        ///                }
        ///            }
        ///        .
        /// </summary>
        internal static string AddProjectStringsExporterSettings_Request {
            get {
                return ResourceManager.GetString("AddProjectStringsExporterSettings_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            {
        ///                &quot;id&quot;: 44,
        ///                &quot;format&quot;: &quot;android&quot;,
        ///                &quot;settings&quot;: {
        ///                    &quot;convertPlaceHolders&quot;: true
        ///                },
        ///                &quot;createdAt&quot;: &quot;2023-09-10T15:10:43+00:00&quot;,
        ///                &quot;updatedAt&quot;: &quot;2023-09-10T15:10:46+00:00&quot;
        ///            }
        ///        .
        /// </summary>
        internal static string AddProjectStringsExporterSettings_Response {
            get {
                return ResourceManager.GetString("AddProjectStringsExporterSettings_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            [
        ///                {
        ///                    &quot;path&quot;: &quot;/format&quot;,
        ///                    &quot;op&quot;: &quot;replace&quot;,
        ///                    &quot;value&quot;: &quot;macosx&quot;
        ///                },
        ///                {
        ///                    &quot;path&quot;: &quot;/settings&quot;,
        ///                    &quot;op&quot;: &quot;replace&quot;,
        ///                    &quot;value&quot;: {
        ///                        &quot;convertPlaceHolders&quot;: false
        ///                    }
        ///                },
        ///            ]
        ///        .
        /// </summary>
        internal static string EditProjectStringsExporterSettings_Request {
            get {
                return ResourceManager.GetString("EditProjectStringsExporterSettings_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            {
        ///                &quot;id&quot;: 44,
        ///                &quot;format&quot;: &quot;macosx&quot;,
        ///                &quot;settings&quot;: {
        ///                    &quot;convertPlaceHolders&quot;: false
        ///                },
        ///                &quot;createdAt&quot;: &quot;2023-09-10T15:10:43+00:00&quot;,
        ///                &quot;updatedAt&quot;: &quot;2023-09-10T15:10:46+00:00&quot;
        ///            }
        ///        .
        /// </summary>
        internal static string EditProjectStringsExporterSettings_Response {
            get {
                return ResourceManager.GetString("EditProjectStringsExporterSettings_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            {
        ///                &quot;id&quot;: 45,
        ///                &quot;format&quot;: &quot;android&quot;,
        ///                &quot;settings&quot;: {
        ///                    &quot;convertPlaceHolders&quot;: true
        ///                },
        ///                &quot;createdAt&quot;: &quot;2023-09-10T15:10:43+00:00&quot;,
        ///                &quot;updatedAt&quot;: &quot;2023-09-10T15:10:46+00:00&quot;
        ///            }
        ///        .
        /// </summary>
        internal static string GetProjectStringsExporterSettings_Response {
            get {
                return ResourceManager.GetString("GetProjectStringsExporterSettings_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            {   
        ///                &quot;data&quot;: [
        ///                    {
        ///                        &quot;data&quot;: {
        ///                            &quot;id&quot;: 45,
        ///                            &quot;format&quot;: &quot;android&quot;,
        ///                            &quot;settings&quot;: {
        ///                                &quot;convertPlaceHolders&quot;: true
        ///                            },
        ///                            &quot;createdAt&quot;: &quot;2023-09-10T15:10:43+00:00&quot;,
        ///                            &quot;updatedAt&quot;: &quot;2023-09-10T15:10:46+00:00&quot;
        ///                        }
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListProjectStringsExporterSettings_Response {
            get {
                return ResourceManager.GetString("ListProjectStringsExporterSettings_Response", resourceCulture);
            }
        }
    }
}
