//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.Tests.Core.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Reports {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reports() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Crowdin.Api.Tests.Core.Resources.Reports", typeof(Reports).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string GenerateReport_Request {
            get {
                return ResourceManager.GetString("GenerateReport_Request", resourceCulture);
            }
        }
        
        internal static string CostEstimationPostEditing_GeneralSchema_Request {
            get {
                return ResourceManager.GetString("CostEstimationPostEditing_GeneralSchema_Request", resourceCulture);
            }
        }
        
        internal static string CostEstimationPostEditing_ByTaskSchema_Request {
            get {
                return ResourceManager.GetString("CostEstimationPostEditing_ByTaskSchema_Request", resourceCulture);
            }
        }
        
        internal static string TranslationCostsPostEditing_GeneralSchema_Request {
            get {
                return ResourceManager.GetString("TranslationCostsPostEditing_GeneralSchema_Request", resourceCulture);
            }
        }
        
        internal static string TranslationCostsPostEditing_ByTaskSchema_Request {
            get {
                return ResourceManager.GetString("TranslationCostsPostEditing_ByTaskSchema_Request", resourceCulture);
            }
        }
        
        internal static string Group_TranslationCostsPostEditing_GeneralSchema_Request {
            get {
                return ResourceManager.GetString("Group_TranslationCostsPostEditing_GeneralSchema_Request", resourceCulture);
            }
        }
        
        internal static string PreTranslateEfficiency_General_Request {
            get {
                return ResourceManager.GetString("PreTranslateEfficiency_General_Request", resourceCulture);
            }
        }
        
        internal static string CommonResponses_ReportStatus {
            get {
                return ResourceManager.GetString("CommonResponses_ReportStatus", resourceCulture);
            }
        }
        
        internal static string PreTranslateEfficiency_ByTask_Request {
            get {
                return ResourceManager.GetString("PreTranslateEfficiency_ByTask_Request", resourceCulture);
            }
        }
    }
}
