//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.Tests.Core.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Reports_Archives {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reports_Archives() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Crowdin.Api.Tests.Core.Resources.Reports_Archives", typeof(Reports_Archives).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Response_Common_Multi {
            get {
                return ResourceManager.GetString("Response_Common_Multi", resourceCulture);
            }
        }
        
        internal static string Response_Common_Single {
            get {
                return ResourceManager.GetString("Response_Common_Single", resourceCulture);
            }
        }
        
        internal static string Response_GroupReportStatus {
            get {
                return ResourceManager.GetString("Response_GroupReportStatus", resourceCulture);
            }
        }
        
        internal static string Request_ExportReportArchive {
            get {
                return ResourceManager.GetString("Request_ExportReportArchive", resourceCulture);
            }
        }
        
        internal static string Response_DownloadLink {
            get {
                return ResourceManager.GetString("Response_DownloadLink", resourceCulture);
            }
        }
    }
}
