//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.Tests.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Reports_SettingsTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reports_SettingsTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.Tests.Core.Resources.Reports_SettingsTemplates", typeof(Reports_SettingsTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///  &quot;mode&quot;: &quot;fuzzy&quot;,
        ///  &quot;config&quot;: {
        ///    &quot;regularRates&quot;: [
        ///      {
        ///        &quot;mode&quot;: &quot;94-90&quot;,
        ///        &quot;value&quot;: 0.1
        ///      }
        ///    ],
        ///    &quot;individualRates&quot;: [
        ///      {
        ///        &quot;languageIds&quot;: [
        ///          &quot;uk&quot;
        ///        ],
        ///        &quot;userIds&quot;: [
        ///          1
        ///        ],
        ///        &quot;rates&quot;: [
        ///          {
        ///            &quot;mode&quot;: &quot;94-90&quot;,
        ///            &quot;value&quot;: 0.1
        ///          }
        ///        ]
        ///      }
        ///    ]
        ///  },
        ///  &quot;name&quot;: &quot;Default template&quot;,
        ///  &quot;currency&quot;: &quot;USD&quot;,
        ///  &quot;unit&quot;: &quot;words&quot;
        ///}.
        /// </summary>
        internal static string AddReportSettingsTemplate_Fuzzy_Request {
            get {
                return ResourceManager.GetString("AddReportSettingsTemplate_Fuzzy_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 1,
        ///    &quot;name&quot;: &quot;Default template&quot;,
        ///    &quot;currency&quot;: &quot;USD&quot;,
        ///    &quot;unit&quot;: &quot;words&quot;,
        ///    &quot;mode&quot;: &quot;fuzzy&quot;,
        ///    &quot;config&quot;: {
        ///      &quot;regularRates&quot;: [
        ///        {
        ///          &quot;mode&quot;: &quot;94-90&quot;,
        ///          &quot;value&quot;: 0.1
        ///        }
        ///      ],
        ///      &quot;individualRates&quot;: [
        ///        {
        ///          &quot;languageIds&quot;: [
        ///            &quot;uk&quot;
        ///          ],
        ///          &quot;userIds&quot;: [
        ///            1
        ///          ],
        ///          &quot;rates&quot;: [
        ///            {
        ///              &quot;mode&quot;: &quot;94-90&quot;,
        ///              &quot;value&quot;: 0.1
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddReportSettingsTemplate_Fuzzy_Response {
            get {
                return ResourceManager.GetString("AddReportSettingsTemplate_Fuzzy_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///  &quot;mode&quot;: &quot;simple&quot;,
        ///
        ///  &quot;config&quot;: {
        ///    &quot;regularRates&quot;: [
        ///      {
        ///        &quot;mode&quot;: &quot;tm_match&quot;,
        ///        &quot;value&quot;: 0.1
        ///      }
        ///    ],
        ///    &quot;individualRates&quot;: [
        ///      {
        ///        &quot;languageIds&quot;: [
        ///          &quot;uk&quot;
        ///        ],
        ///        &quot;userIds&quot;: [
        ///          1
        ///        ],
        ///        &quot;rates&quot;: [
        ///          {
        ///            &quot;mode&quot;: &quot;tm_match&quot;,
        ///            &quot;value&quot;: 0.1
        ///          }
        ///        ]
        ///      }
        ///    ]
        ///  },
        ///  &quot;name&quot;: &quot;Default template&quot;,
        ///  &quot;currency&quot;: &quot;USD&quot;,
        ///  &quot;unit&quot;: &quot;words&quot;,
        ///}.
        /// </summary>
        internal static string AddReportSettingsTemplate_Simple_Request {
            get {
                return ResourceManager.GetString("AddReportSettingsTemplate_Simple_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 1,
        ///    &quot;name&quot;: &quot;Default template&quot;,
        ///    &quot;currency&quot;: &quot;USD&quot;,
        ///    &quot;unit&quot;: &quot;words&quot;,
        ///    &quot;mode&quot;: &quot;simple&quot;,
        ///    &quot;config&quot;: {
        ///      &quot;regularRates&quot;: [
        ///        {
        ///          &quot;mode&quot;: &quot;tm_match&quot;,
        ///          &quot;value&quot;: 0.1
        ///        }
        ///      ],
        ///      &quot;individualRates&quot;: [
        ///        {
        ///          &quot;languageIds&quot;: [
        ///            &quot;uk&quot;
        ///          ],
        ///          &quot;userIds&quot;: [
        ///            1
        ///          ],
        ///          &quot;rates&quot;: [
        ///            {
        ///              &quot;mode&quot;: &quot;tm_match&quot;,
        ///              &quot;value&quot;: 0.1        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddReportSettingsTemplate_Simple_Response {
            get {
                return ResourceManager.GetString("AddReportSettingsTemplate_Simple_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///
        ///    &quot;path&quot;: &quot;currency&quot;,
        ///    &quot;op&quot;: &quot;replace&quot;,
        ///
        ///    &quot;value&quot;: &quot;AUD&quot;
        ///  },
        ///
        ///  {
        ///
        ///    &quot;path&quot;: &quot;mode&quot;,
        ///    &quot;op&quot;: &quot;replace&quot;,
        ///    &quot;value&quot;: &quot;fuzzy&quot;
        ///  }
        ///].
        /// </summary>
        internal static string EditReportSettingsTemplate_Request {
            get {
                return ResourceManager.GetString("EditReportSettingsTemplate_Request", resourceCulture);
            }
        }
    }
}
