//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.Tests.Core.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Screenshots {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Screenshots() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Crowdin.Api.Tests.Core.Resources.Screenshots", typeof(Screenshots).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AddScreenshot_Request {
            get {
                return ResourceManager.GetString("AddScreenshot_Request", resourceCulture);
            }
        }
        
        internal static string AddScreenshot_Response {
            get {
                return ResourceManager.GetString("AddScreenshot_Response", resourceCulture);
            }
        }
        
        internal static string EditScreenshot_Response {
            get {
                return ResourceManager.GetString("EditScreenshot_Response", resourceCulture);
            }
        }
        
        internal static string GetScreenshot_Response
        {
            get
            {
                return ResourceManager.GetString("GetScreenshot_Response", resourceCulture);
            }
        }
        
        internal static string ListScreenshots_Response
        {
            get
            {
                return ResourceManager.GetString("ListScreenshots_Response", resourceCulture);
            }
        }
    }
}
