//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.Tests.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.Tests.Core.Resources.SourceStrings", typeof(SourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;data&quot;: {
        ///        &quot;id&quot;: 2814,
        ///        &quot;projectId&quot;: 2,
        ///        &quot;fileId&quot;: 48,
        ///        &quot;branchId&quot;: 12,
        ///        &quot;directoryId&quot;: 13,
        ///        &quot;identifier&quot;: &quot;name&quot;,
        ///        &quot;text&quot;: &quot;Not all videos are shown to users. See more&quot;,
        ///        &quot;type&quot;: &quot;text&quot;,
        ///        &quot;context&quot;: &quot;shown on main page&quot;,
        ///        &quot;maxLength&quot;: 35,
        ///        &quot;isHidden&quot;: false,
        ///        &quot;isDuplicate&quot;: true,
        ///        &quot;masterStringId&quot;: 1,
        ///        &quot;revision&quot;: 1,
        ///        &quot;hasPlurals&quot;: false,
        ///        &quot;isIcu&quot;: fal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommonResponses_SingleStringInArray {
            get {
                return ResourceManager.GetString("CommonResponses_SingleStringInArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///
        ///    &quot;path&quot;: &quot;/2814/isHidden&quot;,
        ///    &quot;op&quot;: &quot;replace&quot;,
        ///    &quot;value&quot;: true
        ///  },
        ///  {
        ///
        ///    &quot;path&quot;: &quot;/2814/context&quot;,
        ///    &quot;op&quot;: &quot;replace&quot;,
        ///    &quot;value&quot;: &quot;some context&quot;
        ///  },
        ///  {
        ///
        ///    &quot;path&quot;: &quot;/-&quot;,
        ///    &quot;op&quot;: &quot;add&quot;,
        ///    &quot;value&quot;: {
        ///      &quot;text&quot;: &quot;new added string&quot;,
        ///      &quot;identifier&quot;: &quot;a.b.c&quot;,
        ///
        ///      &quot;fileId&quot;: 5,
        ///      &quot;context&quot;: &quot;context for new string&quot;,
        ///      &quot;isHidden&quot;: false
        ///    }
        ///  },
        ///  {
        ///
        ///    &quot;path&quot;: &quot;/2815&quot;,
        ///    &quot;op&quot;: &quot;remove&quot;
        ///  }
        ///].
        /// </summary>
        internal static string StringBatchOperations_Request {
            get {
                return ResourceManager.GetString("StringBatchOperations_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;data&quot;: {
        ///        &quot;id&quot;: 2814,
        ///        &quot;projectId&quot;: 2,
        ///        &quot;fileId&quot;: 48,
        ///        &quot;branchId&quot;: 12,
        ///        &quot;directoryId&quot;: 13,
        ///        &quot;identifier&quot;: &quot;name&quot;,
        ///        &quot;text&quot;: &quot;Not all videos are shown to users. See more&quot;,
        ///        &quot;type&quot;: &quot;text&quot;,
        ///        &quot;context&quot;: &quot;shown on main page&quot;,
        ///        &quot;maxLength&quot;: 35,
        ///        &quot;isHidden&quot;: false,
        ///        &quot;isDuplicate&quot;: true,
        ///        &quot;masterStringId&quot;: 1,
        ///        &quot;revision&quot;: 1,
        ///        &quot;hasPlurals&quot;: false,
        ///        &quot;isIcu&quot;: fal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringBatchOperations_Response {
            get {
                return ResourceManager.GetString("StringBatchOperations_Response", resourceCulture);
            }
        }
    }
}
