//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.Tests.Core.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SourceStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SourceStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Crowdin.Api.Tests.Core.Resources.SourceStrings", typeof(SourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string StringBatchOperations_Response {
            get {
                return ResourceManager.GetString("StringBatchOperations_Response", resourceCulture);
            }
        }
        
        internal static string StringBatchOperations_Request {
            get {
                return ResourceManager.GetString("StringBatchOperations_Request", resourceCulture);
            }
        }
        
        internal static string CommonResponses_SingleStringInArray {
            get {
                return ResourceManager.GetString("CommonResponses_SingleStringInArray", resourceCulture);
            }
        }
        
        internal static string StringBatchOperations_Response_NoPagination {
            get {
                return ResourceManager.GetString("StringBatchOperations_Response_NoPagination", resourceCulture);
            }
        }
        
        internal static string CommonResponses_UploadStrings {
            get {
                return ResourceManager.GetString("CommonResponses_UploadStrings", resourceCulture);
            }
        }
        
        internal static string UploadStrings_Request {
            get {
                return ResourceManager.GetString("UploadStrings_Request", resourceCulture);
            }
        }
    }
}
