//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.Tests.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Webhooks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Webhooks() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.Tests.Core.Resources.Webhooks", typeof(Webhooks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;Proofread&quot;,
        ///  &quot;url&quot;: &quot;https://webhook.site/1c20d9b5-6e6a-4522-974d-9da7ea7595c9&quot;,
        ///  &quot;events&quot;: [
        ///    &quot;file.approved&quot;,
        ///    &quot;translation.updated&quot;,
        ///    &quot;suggestion.deleted&quot;
        ///  ],
        ///  &quot;requestType&quot;: &quot;POST&quot;,
        ///  &quot;isActive&quot;: true,
        ///  &quot;batchingEnabled&quot;: true,
        ///  &quot;contentType&quot;: &quot;application/json&quot;,
        ///  &quot;headers&quot;: {
        ///     &quot;apiKey&quot;:&quot;key&quot;
        ///    },
        ///    &quot;payload&quot;: {
        ///      &quot;file.approved&quot;: {
        ///        &quot;eventType&quot;: &quot;{{event}}&quot;       
        ///      }
        ///    }
        ///}.
        /// </summary>
        internal static string AddWebhook_Request {
            get {
                return ResourceManager.GetString("AddWebhook_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 4,
        ///    &quot;projectId&quot;: 2,
        ///    &quot;name&quot;: &quot;Proofread&quot;,
        ///    &quot;url&quot;: &quot;https://webhook.site/1c20d9b5-6e6a-4522-974d-9da7ea7595c9&quot;,
        ///    &quot;events&quot;: [
        ///      &quot;file.approved&quot;,
        ///
        ///      &quot;translation.updated&quot;,
        ///
        ///      &quot;suggestion.deleted&quot;
        ///    ],
        ///  &quot;headers&quot;: {
        ///     &quot;apiKey&quot;:&quot;key&quot;
        ///    },
        ///    &quot;payload&quot;: {
        ///      &quot;file.approved&quot;: {
        ///        &quot;eventType&quot;: &quot;{{event}}&quot;       
        ///      }
        ///    },
        ///    &quot;isActive&quot;: true,
        ///    &quot;batchingEnabled&quot;: true,
        ///    &quot;requestType&quot;: &quot;GET&quot;,
        ///    &quot;contentType&quot;: &quot;appl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddWebhook_Response {
            get {
                return ResourceManager.GetString("AddWebhook_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///
        ///      &quot;path&quot;: &quot;/name&quot;,
        ///      &quot;op&quot;: &quot;replace&quot;,
        ///      &quot;value&quot;: &quot;Proofread&quot;
        ///    },
        ///    {
        ///
        ///      &quot;path&quot;: &quot;/requestType&quot;,
        ///      &quot;op&quot;: &quot;replace&quot;,
        ///      &quot;value&quot;: &quot;GET&quot;
        ///    }
        ///  ].
        /// </summary>
        internal static string EditWebhook_Request {
            get {
                return ResourceManager.GetString("EditWebhook_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 4,
        ///    &quot;projectId&quot;: 2,
        ///    &quot;name&quot;: &quot;Proofread&quot;,
        ///    &quot;url&quot;: &quot;https://webhook.site/1c20d9b5-6e6a-4522-974d-9da7ea7595c9&quot;,
        ///    &quot;events&quot;: [
        ///      &quot;file.approved&quot;
        ///    ],
        ///   &quot;headers&quot;: {
        ///     &quot;apiKey&quot;:&quot;key&quot;
        ///    },
        ///    &quot;payload&quot;: {
        ///      &quot;file.approved&quot;: {
        ///        &quot;eventType&quot;: &quot;{{event}}&quot;       
        ///      }
        ///    },
        ///    &quot;isActive&quot;: true,
        ///    &quot;batchingEnabled&quot;: true,
        ///    &quot;requestType&quot;: &quot;GET&quot;,
        ///    &quot;contentType&quot;: &quot;application/json&quot;,
        ///    &quot;createdAt&quot;: &quot;2019-09-23T09:19:07+00:00&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EditWebhook_Response {
            get {
                return ResourceManager.GetString("EditWebhook_Response", resourceCulture);
            }
        }
    }
}
