//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.Tests.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Webhooks_Organization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Webhooks_Organization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.Tests.Core.Resources.Webhooks_Organization", typeof(Webhooks_Organization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///  &quot;events&quot;: [
        ///    &quot;project.created&quot;
        ///  ],
        ///  &quot;name&quot;: &quot;Proofread&quot;,
        ///  &quot;url&quot;: &quot;https://webhook.site/1c20d9b5-6e6a-4522-974d-9da7ea7595c9&quot;,
        ///  &quot;requestType&quot;: &quot;POST&quot;,
        ///  &quot;isActive&quot;: true,
        ///  &quot;batchingEnabled&quot;: true,
        ///  &quot;contentType&quot;: &quot;application/json&quot;,
        ///  &quot;headers&quot;: {}
        ///}.
        /// </summary>
        internal static string AddWebhook_Request {
            get {
                return ResourceManager.GetString("AddWebhook_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 4,
        ///    &quot;name&quot;: &quot;Proofread&quot;,
        ///    &quot;url&quot;: &quot;https://webhook.site/1c20d9b5-6e6a-4522-974d-9da7ea7595c9&quot;,
        ///    &quot;events&quot;: [
        ///      &quot;project.created&quot;
        ///    ],
        ///    &quot;headers&quot;: { },
        ///    &quot;payload&quot;: {
        ///      &quot;project.created&quot;: {
        ///        &quot;event&quot;: &quot;{{event}}&quot;,
        ///        &quot;project&quot;: {
        ///          &quot;id&quot;: &quot;{{projectId}}&quot;,
        ///          &quot;userId&quot;: &quot;{{projectUserId}}&quot;,
        ///          &quot;sourceLanguageId&quot;: &quot;{{projectSourceLanguageId}}&quot;,
        ///          &quot;targetLanguageIds&quot;: &quot;{{projectTargetLanguageIds}}&quot;,
        ///          &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommonResponses_SingleWebhook {
            get {
                return ResourceManager.GetString("CommonResponses_SingleWebhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;path&quot;: &quot;/name&quot;,
        ///    &quot;op&quot;: &quot;replace&quot;,
        ///    &quot;value&quot;: &quot;Proofread&quot;
        ///  },
        ///  {
        ///    &quot;path&quot;: &quot;/events&quot;,
        ///    &quot;op&quot;: &quot;replace&quot;,
        ///    &quot;value&quot;: [
        ///      &quot;project.created&quot;,
        ///      &quot;project.deleted&quot;
        ///    ]
        ///  },
        ///].
        /// </summary>
        internal static string EditWebhook_Request {
            get {
                return ResourceManager.GetString("EditWebhook_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;data&quot;: {
        ///        &quot;id&quot;: 4,
        ///        &quot;name&quot;: &quot;Proofread&quot;,
        ///        &quot;url&quot;: &quot;https://webhook.site/1c20d9b5-6e6a-4522-974d-9da7ea7595c9&quot;,
        ///        &quot;events&quot;: [
        ///          &quot;project.created&quot;
        ///        ],
        ///        &quot;headers&quot;: { },
        ///        &quot;payload&quot;: {
        ///          &quot;project.created&quot;: {
        ///            &quot;event&quot;: &quot;{{event}}&quot;,
        ///            &quot;project&quot;: {
        ///              &quot;id&quot;: &quot;{{projectId}}&quot;,
        ///              &quot;userId&quot;: &quot;{{projectUserId}}&quot;,
        ///              &quot;sourceLanguageId&quot;: &quot;{{projectSourceLanguageId} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListWebhooks_Response {
            get {
                return ResourceManager.GetString("ListWebhooks_Response", resourceCulture);
            }
        }
    }
}
