//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.UnitTesting.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AI_Providers {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AI_Providers() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Crowdin.Api.UnitTesting.Resources.AI_Providers", typeof(AI_Providers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CommonResponses_Multi {
            get {
                return ResourceManager.GetString("CommonResponses_Multi", resourceCulture);
            }
        }
        
        internal static string AddAiProvider_Request {
            get {
                return ResourceManager.GetString("AddAiProvider_Request", resourceCulture);
            }
        }
        
        internal static string CommonResponses_Single {
            get {
                return ResourceManager.GetString("CommonResponses_Single", resourceCulture);
            }
        }
        
        internal static string EditAiProvider_Request {
            get {
                return ResourceManager.GetString("EditAiProvider_Request", resourceCulture);
            }
        }
        
        internal static string ListAiProviderModels_Response {
            get {
                return ResourceManager.GetString("ListAiProviderModels_Response", resourceCulture);
            }
        }
        
        internal static string Serialization_AiProvider_Credentials_OpenAi {
            get {
                return ResourceManager.GetString("Serialization_AiProvider_Credentials_OpenAi", resourceCulture);
            }
        }
        
        internal static string Serialization_AiProvider_Credentials_AzureOpenAi {
            get {
                return ResourceManager.GetString("Serialization_AiProvider_Credentials_AzureOpenAi", resourceCulture);
            }
        }
        
        internal static string Serialization_AiProvider_Credentials_GoogleGemini {
            get {
                return ResourceManager.GetString("Serialization_AiProvider_Credentials_GoogleGemini", resourceCulture);
            }
        }
        
        internal static string Serialization_AiProvider_Credentials_MistralAi {
            get {
                return ResourceManager.GetString("Serialization_AiProvider_Credentials_MistralAi", resourceCulture);
            }
        }
        
        internal static string Serialization_AiProvider_Credentials_Anthropic {
            get {
                return ResourceManager.GetString("Serialization_AiProvider_Credentials_Anthropic", resourceCulture);
            }
        }
        
        internal static string Serialization_AiProvider_Credentials_CustomAi {
            get {
                return ResourceManager.GetString("Serialization_AiProvider_Credentials_CustomAi", resourceCulture);
            }
        }
        
        internal static string ListSupportedAiProviderModels_Response {
            get {
                return ResourceManager.GetString("ListSupportedAiProviderModels_Response", resourceCulture);
            }
        }
    }
}
