//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.UnitTesting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AI_RequestLogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AI_RequestLogs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.UnitTesting.Resources.AI_RequestLogs", typeof(AI_RequestLogs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property
        ///   when looking up localized resources.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///     "data": [
        ///       {
        ///         "id": 12345,
        ///         "requestId": "9d3b1c4e-2f3a-4b5c-8d6e-7f8a9b0c1d2e",
        ///         "createdAt": "2026-01-01T10:00:00+00:00",
        ///         "status": "success",
        ///         "httpStatus": 200,
        ///         "model": "gpt-5.6-sol",
        ///         "sourceAction": "ai_gateway",
        ///         "promptAction": "pre_translate",
        ///         "systemCredentials": false,
        ///         "isAutoTriggered": false,
        ///         "durationMs": 842,
        ///         "inputTokens": 512,
        ///         "outputTokens": 128,
        ///         "totalCost": 0.012345,
        ///         "userId": 42,
        ///         "projectId": 8,
        ///         "promptId": 5,
        ///         "aiProviderId": 3,
        ///         "tokenName": "Token name",
        ///         "oauthClientId": "gpbccUFxAKZDrLm5Nq8t",
        ///         "oauthClientName": "AI Pipeline",
        ///         "ip": "203.0.113.42",
        ///         "userAgent": "Mozilla/5.0",
        ///         "error": null
        ///       },
        ///       {
        ///         "id": 12346,
        ///         "requestId": "8c2b1c4e-2f3a-4b5c-8d6e-7f8a9b0c1d2e",
        ///         "createdAt": "2026-01-01T10:01:00+00:00",
        ///         "status": "pending",
        ///         "httpStatus": null,
        ///         "model": "gpt-5.6-sol",
        ///         "sourceAction": "ai_proxy",
        ///         "promptAction": null,
        ///         "systemCredentials": true,
        ///         "isAutoTriggered": true,
        ///         "durationMs": null,
        ///         "inputTokens": null,
        ///         "outputTokens": null,
        ///         "totalCost": null,
        ///         "userId": null,
        ///         "projectId": null,
        ///         "promptId": null,
        ///         "aiProviderId": 3,
        ///         "tokenName": null,
        ///         "oauthClientId": null,
        ///         "oauthClientName": null,
        ///         "ip": null,
        ///         "userAgent": null,
        ///         "error": null
        ///       }
        ///     ],
        ///     "pagination": {
        ///       "offset": 0,
        ///       "limit": 25
        ///     }
        ///   }
        /// </summary>
        internal static string ListAiRequestLogs_Response {
            get {
                return ResourceManager.GetString("ListAiRequestLogs_Response", resourceCulture);
            }
        }
    }
}
