//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.UnitTesting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Glossaries_Terms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Glossaries_Terms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.UnitTesting.Resources.Glossaries_Terms", typeof(Glossaries_Terms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;languageId&quot;: &quot;fr&quot;,
        ///&quot;text&quot;: &quot;voir&quot;,
        ///
        ///&quot;description&quot;: &quot;use for pages only (check screenshots)&quot;,
        ///&quot;partOfSpeech&quot;: &quot;subordinating conjunction&quot;
        ///}.
        /// </summary>
        internal static string AddTerm_Request {
            get {
                return ResourceManager.GetString("AddTerm_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 2,
        ///    &quot;userId&quot;: 6,
        ///    &quot;glossaryId&quot;: 1,
        ///    &quot;languageId&quot;: &quot;fr&quot;,
        ///    &quot;text&quot;: &quot;voir&quot;,
        ///    &quot;description&quot;: &quot;use for pages only (check screenshots)&quot;,
        ///    &quot;partOfSpeech&quot;: &quot;subordinating conjunction&quot;,
        ///    &quot;lemma&quot;: &quot;voir&quot;,
        ///    &quot;createdAt&quot;: &quot;2019-09-23T07:19:47+00:00&quot;,
        ///    &quot;updatedAt&quot;: &quot;2019-09-23T07:19:47+00:00&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string AddTerm_Response {
            get {
                return ResourceManager.GetString("AddTerm_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;path&quot;:&quot;/text&quot;,&quot;op&quot;:&quot;replace&quot;,&quot;value&quot;:&quot;Voir&quot;},{&quot;path&quot;:&quot;/description&quot;,&quot;op&quot;:&quot;replace&quot;,&quot;value&quot;:&quot;use for pages only (check screenshots)&quot;},{&quot;path&quot;:&quot;/partOfSpeech&quot;,&quot;op&quot;:&quot;replace&quot;,&quot;value&quot;:&quot;subordinating conjunction&quot;}].
        /// </summary>
        internal static string EditTerm_Request {
            get {
                return ResourceManager.GetString("EditTerm_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 2,
        ///    &quot;userId&quot;: 6,
        ///    &quot;glossaryId&quot;: 6,
        ///    &quot;languageId&quot;: &quot;fr&quot;,
        ///    &quot;text&quot;: &quot;Voir&quot;,
        ///    &quot;description&quot;: &quot;use for pages only (check screenshots)&quot;,
        ///    &quot;partOfSpeech&quot;: &quot;subordinating conjunction&quot;,
        ///    &quot;lemma&quot;: &quot;voir&quot;,
        ///    &quot;createdAt&quot;: &quot;2019-09-23T07:19:47+00:00&quot;,
        ///    &quot;updatedAt&quot;: &quot;2019-09-23T07:19:47+00:00&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string EditTerm_Response {
            get {
                return ResourceManager.GetString("EditTerm_Response", resourceCulture);
            }
        }
    }
}
