//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.UnitTesting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Reports_Archives {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reports_Archives() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.UnitTesting.Resources.Reports_Archives", typeof(Reports_Archives).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;format&quot;: &quot;json&quot;
        ///}.
        /// </summary>
        internal static string Request_ExportReportArchive {
            get {
                return ResourceManager.GetString("Request_ExportReportArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;data&quot;: {
        ///        &quot;id&quot;: 12,
        ///        &quot;scopeType&quot;: &quot;project&quot;,
        ///        &quot;scopeId&quot;: 35,
        ///        &quot;userId&quot;: 35,
        ///        &quot;name&quot;: &quot;string&quot;,
        ///        &quot;webUrl&quot;: &quot;https://crowdin.com&quot;,
        ///        &quot;scheme&quot;: {},
        ///        &quot;createdAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;
        ///      }
        ///    }
        ///  ],
        ///  &quot;pagination&quot;: {
        ///    &quot;offset&quot;: 0,
        ///    &quot;limit&quot;: 25
        ///  }
        ///}.
        /// </summary>
        internal static string Response_Common_Multi {
            get {
                return ResourceManager.GetString("Response_Common_Multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 12,
        ///    &quot;scopeType&quot;: &quot;project&quot;,
        ///    &quot;scopeId&quot;: 35,
        ///    &quot;userId&quot;: 35,
        ///    &quot;name&quot;: &quot;string&quot;,
        ///    &quot;webUrl&quot;: &quot;https://crowdin.com/project/project-identifier/reports/archive/1&quot;,
        ///    &quot;scheme&quot;: {},
        ///    &quot;createdAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string Response_Common_Single {
            get {
                return ResourceManager.GetString("Response_Common_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;url&quot;: &quot;https://crowdin.com&quot;,
        ///    &quot;expireIn&quot;: &quot;2019-09-20T10:31:21+00:00&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string Response_DownloadLink {
            get {
                return ResourceManager.GetString("Response_DownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;identifier&quot;: &quot;50fb3506-4127-4ba8-8296-f97dc7e3e0c3&quot;,
        ///    &quot;status&quot;: &quot;finished&quot;,
        ///    &quot;progress&quot;: 100,
        ///    &quot;attributes&quot;: {
        ///      &quot;format&quot;: &quot;xlsx&quot;,
        ///      &quot;reportName&quot;: &quot;costs-estimation&quot;,
        ///      &quot;schema&quot;: {}
        ///    },
        ///    &quot;createdAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;updatedAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;startedAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;finishedAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string Response_GroupReportStatus {
            get {
                return ResourceManager.GetString("Response_GroupReportStatus", resourceCulture);
            }
        }
    }
}
