//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.UnitTesting.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Reports_UserSettingsTemplates {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reports_UserSettingsTemplates() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Crowdin.Api.UnitTesting.Resources.Reports_UserSettingsTemplates", typeof(Reports_UserSettingsTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CommonResponses_List {
            get {
                return ResourceManager.GetString("CommonResponses_List", resourceCulture);
            }
        }
        
        internal static string AddUserReportSettingsTemplate_Request {
            get {
                return ResourceManager.GetString("AddUserReportSettingsTemplate_Request", resourceCulture);
            }
        }
        
        internal static string CommonResponses_Single {
            get {
                return ResourceManager.GetString("CommonResponses_Single", resourceCulture);
            }
        }
        
        internal static string EditUserReportSettingsTemplate_Request {
            get {
                return ResourceManager.GetString("EditUserReportSettingsTemplate_Request", resourceCulture);
            }
        }
    }
}
