//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.UnitTesting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Screenshots {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Screenshots() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.UnitTesting.Resources.Screenshots", typeof(Screenshots).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;storageId&quot;: 71,
        ///  &quot;name&quot;: &quot;translate_with_siri.jpg&quot;,
        ///  &quot;autoTag&quot;: true,
        ///  &quot;labelIds&quot;: [
        ///    0, 1
        ///  ]
        ///}.
        /// </summary>
        internal static string AddScreenshot_Request {
            get {
                return ResourceManager.GetString("AddScreenshot_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 2,
        ///    &quot;userId&quot;: 6,
        ///    &quot;url&quot;: &quot;https://production-enterprise-screenshots.downloads.crowdin.com/992000002/6/2/middle.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&amp;X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Credential=AKIAIGJKLQV66ZXPMMEA%2F20190923%2Fus-east-1%2Fs3%2Faws4_request&amp;X-Amz-Date=20190923T093016Z&amp;X-Amz-SignedHeaders=host&amp;X-Amz-Expires=120&amp;X-Amz-Signature=8df06f57594f7d1804b7c037629f6916224415e9b935c4f6619fbe002fb25e73&quot;,
        ///    &quot;name&quot;: &quot;translate_with_siri.jpg&quot;,
        ///    &quot;size&quot;: {
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddScreenshot_Response {
            get {
                return ResourceManager.GetString("AddScreenshot_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///          &quot;data&quot;: {
        ///            &quot;id&quot;: 2,
        ///            &quot;userId&quot;: 6,
        ///            &quot;url&quot;: &quot;https://production-enterprise-screenshots.downloads.crowdin.com/992000002/6/2/middle.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&amp;X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Credential=AKIAIGJKLQV66ZXPMMEA%2F20190923%2Fus-east-1%2Fs3%2Faws4_request&amp;X-Amz-Date=20190923T093016Z&amp;X-Amz-SignedHeaders=host&amp;X-Amz-Expires=120&amp;X-Amz-Signature=8df06f57594f7d1804b7c037629f6916224415e9b935c4f6619fbe002fb25e73&quot;,
        ///            &quot;name&quot;: &quot;tra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EditScreenshot_Response {
            get {
                return ResourceManager.GetString("EditScreenshot_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 2,
        ///    &quot;userId&quot;: 6,
        ///    &quot;url&quot;: &quot;https://production-enterprise-screenshots.downloads.crowdin.com/992000002/6/2/middle.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&amp;X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Credential=AKIAIGJKLQV66ZXPMMEA%2F20190923%2Fus-east-1%2Fs3%2Faws4_request&amp;X-Amz-Date=20190923T093016Z&amp;X-Amz-SignedHeaders=host&amp;X-Amz-Expires=120&amp;X-Amz-Signature=8df06f57594f7d1804b7c037629f6916224415e9b935c4f6619fbe002fb25e73&quot;,
        ///    &quot;name&quot;: &quot;translate_with_siri.jpg&quot;,
        ///    &quot;size&quot;: {
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetScreenshot_Response {
            get {
                return ResourceManager.GetString("GetScreenshot_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;data&quot;: {
        ///        &quot;id&quot;: 2,
        ///        &quot;userId&quot;: 6,
        ///        &quot;url&quot;: &quot;https://production-enterprise-screenshots.downloads.crowdin.com/992000002/6/2/middle.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&amp;X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Credential=AKIAIGJKLQV66ZXPMMEA%2F20190923%2Fus-east-1%2Fs3%2Faws4_request&amp;X-Amz-Date=20190923T093016Z&amp;X-Amz-SignedHeaders=host&amp;X-Amz-Expires=120&amp;X-Amz-Signature=8df06f57594f7d1804b7c037629f6916224415e9b935c4f6619fbe002fb25e73&quot;,
        ///        &quot;webUrl&quot;: &quot;h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListScreenshots_Response {
            get {
                return ResourceManager.GetString("ListScreenshots_Response", resourceCulture);
            }
        }
    }
}
