//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.UnitTesting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.UnitTesting.Resources.SourceStrings", typeof(SourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;data&quot;: {
        ///        &quot;id&quot;: 2814,
        ///        &quot;projectId&quot;: 2,
        ///        &quot;fileId&quot;: 48,
        ///        &quot;branchId&quot;: 12,
        ///        &quot;directoryId&quot;: 13,
        ///        &quot;identifier&quot;: &quot;name&quot;,
        ///        &quot;text&quot;: &quot;Not all videos are shown to users. See more&quot;,
        ///        &quot;type&quot;: &quot;text&quot;,
        ///        &quot;context&quot;: &quot;shown on main page&quot;,
        ///        &quot;maxLength&quot;: 35,
        ///        &quot;isHidden&quot;: false,
        ///        &quot;isDuplicate&quot;: true,
        ///        &quot;masterStringId&quot;: 1,
        ///        &quot;revision&quot;: 1,
        ///        &quot;hasPlurals&quot;: false,
        ///        &quot;isIcu&quot;: fal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommonResponses_SingleStringInArray {
            get {
                return ResourceManager.GetString("CommonResponses_SingleStringInArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;identifier&quot;: &quot;50fb3506-4127-4ba8-8296-f97dc7e3e0c3&quot;,
        ///    &quot;status&quot;: &quot;finished&quot;,
        ///    &quot;progress&quot;: 100,
        ///    &quot;attributes&quot;: {
        ///      &quot;branchId&quot;: 38,
        ///      &quot;storageId&quot;: 38,
        ///      &quot;fileType&quot;: &quot;android&quot;,
        ///      &quot;parserVersion&quot;: 8,
        ///      &quot;labelIds&quot;: [
        ///        1,
        ///        2
        ///      ],
        ///      &quot;importOptions&quot;: {
        ///        &quot;firstLineContainsHeader&quot;: false,
        ///        &quot;importTranslations&quot;: true,
        ///        &quot;scheme&quot;: {
        ///          &quot;identifier&quot;: 0,
        ///          &quot;sourcePhrase&quot;: 1,
        ///          &quot;en&quot;: 2,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommonResponses_UploadStrings {
            get {
                return ResourceManager.GetString("CommonResponses_UploadStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///        &quot;data&quot;: [
        ///            {
        ///                &quot;data&quot;: {
        ///                    &quot;id&quot;: 335299,
        ///                    &quot;projectId&quot;: 81,
        ///                    &quot;branchId&quot;: 14201,
        ///                    &quot;identifier&quot;: &quot;common.readableTimeSpan.time_day&quot;,
        ///                    &quot;text&quot;: {
        ///                        &quot;one&quot;: &quot;{{count}} day&quot;,
        ///                        &quot;other&quot;: &quot;{{count}} days&quot;
        ///                    },
        ///                    &quot;type&quot;: &quot;text&quot;,
        ///                    &quot;context&quot;: &quot;common.readableTimeSpan.time_day&quot;,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListStrings_i18Next_bug {
            get {
                return ResourceManager.GetString("ListStrings_i18Next_bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;data&quot;: {
        ///        &quot;id&quot;: 2814,
        ///        &quot;projectId&quot;: 2,
        ///        &quot;branchId&quot;: 12,
        ///        &quot;identifier&quot;: &quot;name&quot;,
        ///        &quot;text&quot;: &quot;Not all videos are shown to users. See more&quot;,
        ///        &quot;type&quot;: &quot;text&quot;,
        ///        &quot;context&quot;: &quot;shown on main page&quot;,
        ///        &quot;maxLength&quot;: 35,
        ///        &quot;isHidden&quot;: false,
        ///        &quot;isDuplicate&quot;: true,
        ///        &quot;masterStringId&quot;: 1,
        ///        &quot;hasPlurals&quot;: false,
        ///        &quot;isIcu&quot;: false,
        ///        &quot;labelIds&quot;: [
        ///          3
        ///        ],
        ///        &quot;webUrl&quot;: &quot;htt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListStrings_StringText {
            get {
                return ResourceManager.GetString("ListStrings_StringText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///
        ///    &quot;path&quot;: &quot;/2814/isHidden&quot;,
        ///    &quot;op&quot;: &quot;replace&quot;,
        ///    &quot;value&quot;: true
        ///  },
        ///  {
        ///
        ///    &quot;path&quot;: &quot;/2814/context&quot;,
        ///    &quot;op&quot;: &quot;replace&quot;,
        ///    &quot;value&quot;: &quot;some context&quot;
        ///  },
        ///  {
        ///
        ///    &quot;path&quot;: &quot;/-&quot;,
        ///    &quot;op&quot;: &quot;add&quot;,
        ///    &quot;value&quot;: {
        ///      &quot;text&quot;: &quot;new added string&quot;,
        ///      &quot;identifier&quot;: &quot;a.b.c&quot;,
        ///
        ///      &quot;fileId&quot;: 5,
        ///      &quot;context&quot;: &quot;context for new string&quot;,
        ///      &quot;isHidden&quot;: false
        ///    }
        ///  },
        ///  {
        ///
        ///    &quot;path&quot;: &quot;/2815&quot;,
        ///    &quot;op&quot;: &quot;remove&quot;
        ///  }
        ///].
        /// </summary>
        internal static string StringBatchOperations_Request {
            get {
                return ResourceManager.GetString("StringBatchOperations_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;data&quot;: {
        ///        &quot;id&quot;: 2814,
        ///        &quot;projectId&quot;: 2,
        ///        &quot;fileId&quot;: 48,
        ///        &quot;branchId&quot;: 12,
        ///        &quot;directoryId&quot;: 13,
        ///        &quot;identifier&quot;: &quot;name&quot;,
        ///        &quot;text&quot;: &quot;Not all videos are shown to users. See more&quot;,
        ///        &quot;type&quot;: &quot;text&quot;,
        ///        &quot;context&quot;: &quot;shown on main page&quot;,
        ///        &quot;maxLength&quot;: 35,
        ///        &quot;isHidden&quot;: false,
        ///        &quot;isDuplicate&quot;: true,
        ///        &quot;masterStringId&quot;: 1,
        ///        &quot;revision&quot;: 1,
        ///        &quot;hasPlurals&quot;: false,
        ///        &quot;isIcu&quot;: fal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringBatchOperations_Response {
            get {
                return ResourceManager.GetString("StringBatchOperations_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;data&quot;: [
        ///        {
        ///            &quot;data&quot;: {
        ///                &quot;id&quot;: 468549,
        ///                &quot;projectId&quot;: 11,
        ///                &quot;fileId&quot;: 1533,
        ///                &quot;branchId&quot;: null,
        ///                &quot;directoryId&quot;: 1535,
        ///                &quot;identifier&quot;: &quot;bulk_edit_6&quot;,
        ///                &quot;text&quot;: &quot;Batch operations with send patch request&quot;,
        ///                &quot;type&quot;: &quot;text&quot;,
        ///                &quot;context&quot;: &quot;edited context using patch request&quot;,
        ///                &quot;maxLength&quot;: 0,
        ///                &quot;isHidden&quot;: false,
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringBatchOperations_Response_NoPagination {
            get {
                return ResourceManager.GetString("StringBatchOperations_Response_NoPagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;storageId&quot;: 61,
        ///  &quot;branchId&quot;: 34,
        ///  &quot;type&quot;: &quot;xliff&quot;,
        ///  &quot;parserVersion&quot;: 1,
        ///  &quot;labelIds&quot;: [
        ///    1, 2, 3
        ///  ],
        ///  &quot;updateStrings&quot;: true,
        ///  &quot;cleanupMode&quot;: true,
        ///  &quot;importOptions&quot;: {
        ///    &quot;firstLineContainsHeader&quot;: false,
        ///    &quot;importTranslations&quot;: true,
        ///    &quot;scheme&quot;: {
        ///      &quot;identifier&quot;: 0,
        ///      &quot;sourcePhrase&quot;: 1,
        ///      &quot;en&quot;: 2,
        ///      &quot;de&quot;: 3
        ///    }
        ///  },
        ///  &quot;updateOption&quot;: &quot;keep_translations_and_approvals&quot;
        ///}.
        /// </summary>
        internal static string UploadStrings_Request {
            get {
                return ResourceManager.GetString("UploadStrings_Request", resourceCulture);
            }
        }
    }
}
