//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.UnitTesting.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SourceFiles {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SourceFiles() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Crowdin.Api.UnitTesting.Resources.SourceFiles", typeof(SourceFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AddFile_Request {
            get {
                return ResourceManager.GetString("AddFile_Request", resourceCulture);
            }
        }
        
        internal static string AddFile_Response {
            get {
                return ResourceManager.GetString("AddFile_Response", resourceCulture);
            }
        }
        
        internal static string EditFile_Response {
            get {
                return ResourceManager.GetString("EditFile_Response", resourceCulture);
            }
        }
        
        internal static string EditFile_Request {
            get {
                return ResourceManager.GetString("EditFile_Request", resourceCulture);
            }
        }
        
        internal static string AddFile_Docx_Request {
            get {
                return ResourceManager.GetString("AddFile_Docx_Request", resourceCulture);
            }
        }
        
        internal static string DownloadFilePreview_Response {
            get {
                return ResourceManager.GetString("DownloadFilePreview_Response", resourceCulture);
            }
        }
        
        internal static string AddFile_Html_Request {
            get {
                return ResourceManager.GetString("AddFile_Html_Request", resourceCulture);
            }
        }
        
        internal static string AddFile_HtmlWithFrontMatter_Request {
            get {
                return ResourceManager.GetString("AddFile_HtmlWithFrontMatter_Request", resourceCulture);
            }
        }
        
        internal static string AddFile_MdxV1_Request {
            get {
                return ResourceManager.GetString("AddFile_MdxV1_Request", resourceCulture);
            }
        }
        
        internal static string AddFile_JavaScript_Request {
            get {
                return ResourceManager.GetString("AddFile_JavaScript_Request", resourceCulture);
            }
        }
        
        internal static string AddFile_JavaScript_Response {
            get {
                return ResourceManager.GetString("AddFile_JavaScript_Response", resourceCulture);
            }
        }
        
        internal static string EditFile_JavaScriptRequest {
            get {
                return ResourceManager.GetString("EditFile_JavaScriptRequest", resourceCulture);
            }
        }
        
        internal static string EditFile_JavaScript_Response {
            get {
                return ResourceManager.GetString("EditFile_JavaScript_Response", resourceCulture);
            }
        }
        
        internal static string GetFileResource_Response {
            get {
                return ResourceManager.GetString("GetFileResource_Response", resourceCulture);
            }
        }
    }
}
