//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.UnitTesting.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringCorrections {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringCorrections() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Crowdin.Api.UnitTesting.Resources.StringCorrections", typeof(StringCorrections).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ListCorrections_Response {
            get {
                return ResourceManager.GetString("ListCorrections_Response", resourceCulture);
            }
        }
        
        internal static string AddCorrection_Request {
            get {
                return ResourceManager.GetString("AddCorrection_Request", resourceCulture);
            }
        }
        
        internal static string AddCorrection_Response {
            get {
                return ResourceManager.GetString("AddCorrection_Response", resourceCulture);
            }
        }
        
        internal static string GetCorrection_Response {
            get {
                return ResourceManager.GetString("GetCorrection_Response", resourceCulture);
            }
        }
        
        internal static string RestoreCorrection_Response {
            get {
                return ResourceManager.GetString("RestoreCorrection_Response", resourceCulture);
            }
        }
    }
}
