//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.UnitTesting.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTranslations {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTranslations() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Crowdin.Api.UnitTesting.Resources.StringTranslations", typeof(StringTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AddTranslation_Request {
            get {
                return ResourceManager.GetString("AddTranslation_Request", resourceCulture);
            }
        }
        
        internal static string AddTranslation_Response {
            get {
                return ResourceManager.GetString("AddTranslation_Response", resourceCulture);
            }
        }
        
        internal static string RestoreTranslation_Response {
            get {
                return ResourceManager.GetString("RestoreTranslation_Response", resourceCulture);
            }
        }
        
        internal static string ListLanguageTranslations_Response {
            get {
                return ResourceManager.GetString("ListLanguageTranslations_Response", resourceCulture);
            }
        }
        
        internal static string TranslationAlignment_Request {
            get {
                return ResourceManager.GetString("TranslationAlignment_Request", resourceCulture);
            }
        }
        
        internal static string TranslationAlignment_Response {
            get {
                return ResourceManager.GetString("TranslationAlignment_Response", resourceCulture);
            }
        }
        
        internal static string ListTranslationsApproval_Response {
            get {
                return ResourceManager.GetString("ListTranslationsApproval_Response", resourceCulture);
            }
        }
        
        internal static string ListTranslationVotes_Response {
            get {
                return ResourceManager.GetString("ListTranslationVotes_Response", resourceCulture);
            }
        }
        
        internal static string TranslationBatchOperations_Request {
            get {
                return ResourceManager.GetString("TranslationBatchOperations_Request", resourceCulture);
            }
        }
        
        internal static string TranslationBatchOperations_Response {
            get {
                return ResourceManager.GetString("TranslationBatchOperations_Response", resourceCulture);
            }
        }
    }
}
