//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.UnitTesting.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StyleGuides {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StyleGuides() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.UnitTesting.Resources.StyleGuides", typeof(StyleGuides).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 1,
        ///    &quot;name&quot;: &quot;My Style Guide&quot;,
        ///    &quot;aiInstructions&quot;: &quot;Use formal language&quot;,
        ///    &quot;userId&quot;: 6,
        ///    &quot;languageIds&quot;: [&quot;en&quot;, &quot;uk&quot;],
        ///    &quot;projectIds&quot;: [1, 2],
        ///    &quot;isShared&quot;: false,
        ///    &quot;webUrl&quot;: &quot;https://crowdin.com/style-guide/1&quot;,
        ///    &quot;downloadLink&quot;: &quot;https://storage.crowdin.com/style-guide-1.pdf&quot;,
        ///    &quot;createdAt&quot;: &quot;2023-09-20T14:05:50+00:00&quot;,
        ///    &quot;updatedAt&quot;: &quot;2023-09-20T14:05:50+00:00&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string StyleGuide {
            get {
                return ResourceManager.GetString("StyleGuide", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;data&quot;: {
        ///        &quot;id&quot;: 1,
        ///        &quot;name&quot;: &quot;My Style Guide&quot;,
        ///        &quot;aiInstructions&quot;: &quot;Use formal language&quot;,
        ///        &quot;userId&quot;: 6,
        ///        &quot;languageIds&quot;: [&quot;en&quot;, &quot;uk&quot;],
        ///        &quot;projectIds&quot;: [1, 2],
        ///        &quot;isShared&quot;: false,
        ///        &quot;webUrl&quot;: &quot;https://crowdin.com/style-guide/1&quot;,
        ///        &quot;downloadLink&quot;: &quot;https://storage.crowdin.com/style-guide-1.pdf&quot;,
        ///        &quot;createdAt&quot;: &quot;2023-09-20T14:05:50+00:00&quot;,
        ///        &quot;updatedAt&quot;: &quot;2023-09-20T14:05:50+00:00&quot;
        ///      }
        ///    }
        ///  ],
        ///  &quot;pagination&quot;: {
        ///    &quot;offset&quot;: 0,
        ///    &quot;limit&quot;: 25
        ///  }
        ///}.
        /// </summary>
        internal static string StyleGuidesList {
            get {
                return ResourceManager.GetString("StyleGuidesList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;My Style Guide&quot;,
        ///  &quot;storageId&quot;: 61
        ///}.
        /// </summary>
        internal static string AddStyleGuideRequest {
            get {
                return ResourceManager.GetString("AddStyleGuideRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 1,
        ///    &quot;name&quot;: &quot;My Style Guide&quot;,
        ///    &quot;aiInstructions&quot;: null,
        ///    &quot;userId&quot;: 6,
        ///    &quot;languageIds&quot;: null,
        ///    &quot;projectIds&quot;: null,
        ///    &quot;isShared&quot;: false,
        ///    &quot;webUrl&quot;: &quot;https://crowdin.com/style-guide/1&quot;,
        ///    &quot;downloadLink&quot;: &quot;https://storage.crowdin.com/style-guide-1.pdf&quot;,
        ///    &quot;createdAt&quot;: &quot;2023-09-20T14:05:50+00:00&quot;,
        ///    &quot;updatedAt&quot;: &quot;2023-09-20T14:05:50+00:00&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string AddStyleGuideResponse {
            get {
                return ResourceManager.GetString("AddStyleGuideResponse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;path&quot;: &quot;/name&quot;,
        ///    &quot;op&quot;: &quot;replace&quot;,
        ///    &quot;value&quot;: &quot;New Style Guide Name&quot;
        ///  }
        ///].
        /// </summary>
        internal static string EditStyleGuideRequest {
            get {
                return ResourceManager.GetString("EditStyleGuideRequest", resourceCulture);
            }
        }
    }
}
