//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.UnitTesting.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tasks {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tasks() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Crowdin.Api.UnitTesting.Resources.Tasks", typeof(Tasks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AddTask_RightRequestJson_VendorGengo_ToneNotSet {
            get {
                return ResourceManager.GetString("AddTask_RightRequestJson_VendorGengo_ToneNotSet", resourceCulture);
            }
        }
        
        internal static string AddTask_RightRequestJson_VendorGengo_ToneInformal {
            get {
                return ResourceManager.GetString("AddTask_RightRequestJson_VendorGengo_ToneInformal", resourceCulture);
            }
        }
        
        internal static string AddTask_RightRequestJson_VendorGengo_ToneOther {
            get {
                return ResourceManager.GetString("AddTask_RightRequestJson_VendorGengo_ToneOther", resourceCulture);
            }
        }
        
        internal static string AddTask_RightRequestJson_VendorManual {
            get {
                return ResourceManager.GetString("AddTask_RightRequestJson_VendorManual", resourceCulture);
            }
        }
        
        internal static string ListTasks {
            get {
                return ResourceManager.GetString("ListTasks", resourceCulture);
            }
        }
        
        internal static string Request_PendingTaskCreateForm {
            get {
                return ResourceManager.GetString("Request_PendingTaskCreateForm", resourceCulture);
            }
        }
        
        internal static string Request_CrowdinLanguageServicePendingTaskCreateForm {
            get {
                return ResourceManager.GetString("Request_CrowdinLanguageServicePendingTaskCreateForm", resourceCulture);
            }
        }
        
        internal static string Request_VendorManualPendingTaskCreateForm {
            get {
                return ResourceManager.GetString("Request_VendorManualPendingTaskCreateForm", resourceCulture);
            }
        }
        
        internal static string Request_EnterprisePendingTaskCreateForm {
            get {
                return ResourceManager.GetString("Request_EnterprisePendingTaskCreateForm", resourceCulture);
            }
        }
        
        internal static string GetTask_Response {
            get {
                return ResourceManager.GetString("GetTask_Response", resourceCulture);
            }
        }
    }
}
