//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.UnitTesting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Users_GroupManagers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Users_GroupManagers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.UnitTesting.Resources.Users_GroupManagers", typeof(Users_GroupManagers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;data&quot;: {
        ///        &quot;id&quot;: 27,
        ///        &quot;user&quot;: {
        ///          &quot;id&quot;: 12,
        ///          &quot;username&quot;: &quot;john_smith&quot;,
        ///          &quot;email&quot;: &quot;jsmith@example.com&quot;,
        ///          &quot;firstName&quot;: &quot;John&quot;,
        ///          &quot;lastName&quot;: &quot;Smith&quot;,
        ///          &quot;status&quot;: &quot;active&quot;,
        ///          &quot;avatarUrl&quot;: &quot;&quot;,
        ///          &quot;createdAt&quot;: &quot;2019-07-11T07:40:22+00:00&quot;,
        ///          &quot;lastSeen&quot;: &quot;2019-10-23T11:44:02+00:00&quot;,
        ///          &quot;twoFactor&quot;: &quot;enabled&quot;,
        ///          &quot;isAdmin&quot;: true,
        ///          &quot;timezone&quot;: &quot;Europe/Kyiv&quot;,
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommonResponses_Multi {
            get {
                return ResourceManager.GetString("CommonResponses_Multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 27,
        ///    &quot;user&quot;: {
        ///      &quot;id&quot;: 12,
        ///      &quot;username&quot;: &quot;john_smith&quot;,
        ///      &quot;email&quot;: &quot;jsmith@example.com&quot;,
        ///      &quot;firstName&quot;: &quot;John&quot;,
        ///      &quot;lastName&quot;: &quot;Smith&quot;,
        ///      &quot;status&quot;: &quot;active&quot;,
        ///      &quot;avatarUrl&quot;: &quot;&quot;,
        ///      &quot;createdAt&quot;: &quot;2019-07-11T07:40:22+00:00&quot;,
        ///      &quot;lastSeen&quot;: &quot;2019-10-23T11:44:02+00:00&quot;,
        ///      &quot;twoFactor&quot;: &quot;enabled&quot;,
        ///      &quot;isAdmin&quot;: true,
        ///      &quot;timezone&quot;: &quot;Europe/Kyiv&quot;,
        ///      &quot;fields&quot;: {
        ///        &quot;some-field-1&quot;: &quot;some value 1&quot;,
        ///        &quot;some-field-2&quot;: 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommonResponses_Single {
            get {
                return ResourceManager.GetString("CommonResponses_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///
        ///    &quot;path&quot;: &quot;/-&quot;,
        ///    &quot;op&quot;: &quot;add&quot;,
        ///    &quot;value&quot;: {
        ///      &quot;userId&quot;: 18
        ///    }
        ///  },
        ///  {
        ///
        ///    &quot;path&quot;: &quot;/24&quot;,
        ///    &quot;op&quot;: &quot;remove&quot;
        ///  }
        ///].
        /// </summary>
        internal static string UpdateGroupManagers_Request {
            get {
                return ResourceManager.GetString("UpdateGroupManagers_Request", resourceCulture);
            }
        }
    }
}
