//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.UnitTesting.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Users {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Users() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Crowdin.Api.UnitTesting.Resources.Users", typeof(Users).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string InviteUser_Request {
            get {
                return ResourceManager.GetString("InviteUser_Request", resourceCulture);
            }
        }
        
        internal static string InviteUser_Response {
            get {
                return ResourceManager.GetString("InviteUser_Response", resourceCulture);
            }
        }
        
        internal static string EditUser_Request {
            get {
                return ResourceManager.GetString("EditUser_Request", resourceCulture);
            }
        }
        
        internal static string EditUser_Response {
            get {
                return ResourceManager.GetString("EditUser_Response", resourceCulture);
            }
        }
        
        internal static string AddProjectMember_Request {
            get {
                return ResourceManager.GetString("AddProjectMember_Request", resourceCulture);
            }
        }
        
        internal static string AddProjectMember_Response {
            get {
                return ResourceManager.GetString("AddProjectMember_Response", resourceCulture);
            }
        }
        
        internal static string ReplaceProjectMemberPermissions_Request {
            get {
                return ResourceManager.GetString("ReplaceProjectMemberPermissions_Request", resourceCulture);
            }
        }
        
        internal static string ReplaceProjectMemberPermissions_Response {
            get {
                return ResourceManager.GetString("ReplaceProjectMemberPermissions_Response", resourceCulture);
            }
        }
        
        internal static string ListProjectMembers_Response {
            get {
                return ResourceManager.GetString("ListProjectMembers_Response", resourceCulture);
            }
        }
        
        internal static string GetProjectMemberPermissions_Response {
            get {
                return ResourceManager.GetString("GetProjectMemberPermissions_Response", resourceCulture);
            }
        }
        
        internal static string ListUsers_Response {
            get {
                return ResourceManager.GetString("ListUsers_Response", resourceCulture);
            }
        }
    }
}
