//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.UnitTesting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Workflows {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Workflows() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.UnitTesting.Resources.Workflows", typeof(Workflows).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 311,
        ///    &quot;title&quot;: &quot;Translate&quot;,
        ///    &quot;type&quot;: &quot;Translate&quot;,
        ///    &quot;languages&quot;: [
        ///      &quot;de&quot;,
        ///      &quot;it&quot;
        ///    ],
        ///    &quot;config&quot;: {
        ///      &quot;assignees&quot;: {
        ///        &quot;de&quot;: [
        ///          346
        ///        ],
        ///        &quot;it&quot;: [
        ///          43
        ///        ]
        ///      }
        ///    }
        ///  }
        ///}.
        /// </summary>
        internal static string GetWorkflowStep_Response {
            get {
                return ResourceManager.GetString("GetWorkflowStep_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 2,
        ///    &quot;title&quot;: &quot;In-house + Machine Translation&quot;,
        ///    &quot;description&quot;: &quot;Combine the efforts of human translators and Machine Translation technology.\\n• Pre-translation - Translation Memory\\n• Pre-translation - Machine Translation\\n• Translation - in-house translators\\n• Proofreading - in-house translators&quot;,
        ///    &quot;groupId&quot;: 2,
        ///    &quot;isDefault&quot;: true
        ///  }
        ///}.
        /// </summary>
        internal static string GetWorkflowTemplate_Response {
            get {
                return ResourceManager.GetString("GetWorkflowTemplate_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;data&quot;: {
        ///        &quot;id&quot;: 311,
        ///        &quot;title&quot;: &quot;Translate&quot;,
        ///        &quot;type&quot;: &quot;Translate&quot;,
        ///        &quot;languages&quot;: [
        ///          &quot;de&quot;,
        ///          &quot;it&quot;
        ///        ],
        ///        &quot;config&quot;: {
        ///          &quot;assignees&quot;: {
        ///            &quot;de&quot;: [
        ///              346
        ///            ],
        ///            &quot;it&quot;: [
        ///              43
        ///            ]
        ///          }
        ///        }
        ///      }
        ///    }
        ///  ],
        ///  &quot;pagination&quot;: {
        ///    &quot;offset&quot;: 0,
        ///    &quot;limit&quot;: 25
        ///  }
        ///}.
        /// </summary>
        internal static string ListWorkflowSteps_Response {
            get {
                return ResourceManager.GetString("ListWorkflowSteps_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;data&quot;: {
        ///        &quot;id&quot;: 2,
        ///        &quot;title&quot;: &quot;In-house + Machine Translation&quot;,
        ///        &quot;description&quot;: &quot;Combine the efforts of human translators and Machine Translation technology.\\n• Pre-translation - Translation Memory\\n• Pre-translation - Machine Translation\\n• Translation - in-house translators\\n• Proofreading - in-house translators&quot;,
        ///        &quot;groupId&quot;: 2,
        ///        &quot;isDefault&quot;: true
        ///      }
        ///    }
        ///  ],
        ///  &quot;pagination&quot;: {
        ///    &quot;offset&quot;: 0,
        ///    &quot;limit&quot;: 25
        ///  }
        ///}.
        /// </summary>
        internal static string ListWorkflowTemplates_Response {
            get {
                return ResourceManager.GetString("ListWorkflowTemplates_Response", resourceCulture);
            }
        }
    }
}
