//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.UnitTesting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AI_FineTuningDatasets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AI_FineTuningDatasets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.UnitTesting.Resources.AI_FineTuningDatasets", typeof(AI_FineTuningDatasets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;identifier&quot;: &quot;50fb3506-4127-4ba8-8296-f97dc7e3e0c3&quot;,
        ///    &quot;status&quot;: &quot;finished&quot;,
        ///    &quot;progress&quot;: 100,
        ///    &quot;attributes&quot;: {
        ///      &quot;projectIds&quot;: [
        ///        1, 2, 3
        ///      ],
        ///      &quot;purpose&quot;: &quot;validation&quot;,
        ///      &quot;dateFrom&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///      &quot;dateTo&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///      &quot;maxFileSize&quot;: 100,
        ///      &quot;minExamplesCount&quot;: 10,
        ///      &quot;maxExamplesCount&quot;: 50
        ///    },
        ///    &quot;createdAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;updatedAt&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommonResponses_AiFineTuningDataset {
            get {
                return ResourceManager.GetString("CommonResponses_AiFineTuningDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;identifier&quot;: &quot;50fb3506-4127-4ba8-8296-f97dc7e3e0c3&quot;,
        ///    &quot;status&quot;: &quot;finished&quot;,
        ///    &quot;progress&quot;: 100,
        ///    &quot;attributes&quot;: {
        ///      &quot;dryRun&quot;: true,
        ///      &quot;hyperparameters&quot;: {
        ///        &quot;batchSize&quot;: 2,
        ///        &quot;learningRateMultiplier&quot;: 0.2,
        ///        &quot;nEpochs&quot;: 200
        ///      },
        ///      &quot;trainingOptions&quot;: {
        ///        &quot;projectIds&quot;: [
        ///          1, 2, 3
        ///        ],
        ///        &quot;dateFrom&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///        &quot;dateTo&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///        &quot;maxFileSize&quot;: 100,
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommonResponses_AiFineTuningJob {
            get {
                return ResourceManager.GetString("CommonResponses_AiFineTuningJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;url&quot;: &quot;https://test.com&quot;,
        ///    &quot;expireIn&quot;: &quot;2019-09-20T10:31:21+00:00&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string CommonResponses_DownloadLink {
            get {
                return ResourceManager.GetString("CommonResponses_DownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;dryRun&quot;: true,
        ///  &quot;hyperparameters&quot;: {
        ///    &quot;batchSize&quot;: 2,
        ///    &quot;learningRateMultiplier&quot;: 0.2,
        ///    &quot;nEpochs&quot;: 200
        ///  },
        ///  &quot;trainingOptions&quot;: {
        ///    &quot;projectIds&quot;: [
        ///      1, 2, 3
        ///    ],
        ///    &quot;dateFrom&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;dateTo&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;maxFileSize&quot;: 100,
        ///    &quot;minExamplesCount&quot;: 10,
        ///    &quot;maxExamplesCount&quot;: 50
        ///  },
        ///  &quot;validationOptions&quot;: {
        ///    &quot;projectIds&quot;: [
        ///      1, 2, 3
        ///    ],
        ///    &quot;dateFrom&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///    &quot;dateTo&quot;: &quot;2019-0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateAiPromptFineTuningJob_Request {
            get {
                return ResourceManager.GetString("CreateAiPromptFineTuningJob_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;projectIds&quot;: [
        ///    1, 2, 3
        ///  ],
        ///  &quot;purpose&quot;: &quot;training&quot;,
        ///  &quot;dateFrom&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///  &quot;dateTo&quot;: &quot;2019-09-23T11:26:54+00:00&quot;,
        ///  &quot;maxFileSize&quot;: 100,
        ///  &quot;minExamplesCount&quot;: 10,
        ///  &quot;maxExamplesCount&quot;: 50
        ///}.
        /// </summary>
        internal static string GenerateAiPromptFineTuningDataset_Request {
            get {
                return ResourceManager.GetString("GenerateAiPromptFineTuningDataset_Request", resourceCulture);
            }
        }
    }
}
