//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.UnitTesting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Teams {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Teams() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.UnitTesting.Resources.Teams", typeof(Teams).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;teamId&quot;: 1,
        ///  &quot;accessToAllWorkflowSteps&quot;: false,
        ///  &quot;managerAccess&quot;: false,
        ///  &quot;permissions&quot;: {
        ///    &quot;it&quot;: {
        ///      &quot;workflowStepIds&quot;: [
        ///        313
        ///      ]
        ///    },
        ///    &quot;de&quot;: {
        ///      &quot;workflowStepIds&quot;: &quot;all&quot;
        ///    }
        ///  },
        ///  &quot;roles&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;translator&quot;,
        ///      &quot;permissions&quot;: {
        ///        &quot;allLanguages&quot;: false,
        ///        &quot;languagesAccess&quot;: {
        ///          &quot;uk&quot;: {
        ///            &quot;allContent&quot;: false,
        ///            &quot;workflowStepIds&quot;: [
        ///              882
        ///            ]
        ///          },
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddTeamToProject_Request {
            get {
                return ResourceManager.GetString("AddTeamToProject_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;skipped&quot;: {
        ///    &quot;id&quot;: 1,
        ///    &quot;hasManagerAccess&quot;: false,
        ///    &quot;hasAccessToAllWorkflowSteps&quot;: false,
        ///    &quot;permissions&quot;: {
        ///      &quot;it&quot;: {
        ///        &quot;workflowStepIds&quot;: [
        ///          313
        ///        ]
        ///      }
        ///    },
        ///    &quot;roles&quot;: [
        ///      {
        ///        &quot;name&quot;: &quot;translator&quot;,
        ///        &quot;permissions&quot;: {
        ///          &quot;allLanguages&quot;: false,
        ///          &quot;languagesAccess&quot;: {
        ///            &quot;uk&quot;: {
        ///              &quot;allContent&quot;: false,
        ///              &quot;workflowStepIds&quot;: [
        ///                882
        ///              ]
        ///            },        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddTeamToProject_Response {
            get {
                return ResourceManager.GetString("AddTeamToProject_Response", resourceCulture);
            }
        }
    }
}
