//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crowdin.Api.UnitTesting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TranslationMemory_Segments {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslationMemory_Segments() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crowdin.Api.UnitTesting.Resources.TranslationMemory_Segments", typeof(TranslationMemory_Segments).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 4,
        ///    &quot;records&quot;: [
        ///      {
        ///        &quot;id&quot;: 1,
        ///        &quot;languageId&quot;: &quot;uk&quot;,
        ///        &quot;text&quot;: &quot;Перекладений текст&quot;,
        ///        &quot;usageCount&quot;: 13,
        ///        &quot;createdBy&quot;: 1,
        ///        &quot;updatedBy&quot;: 1,
        ///        &quot;createdAt&quot;: &quot;2019-09-16T13:48:04+00:00&quot;,
        ///        &quot;updatedAt&quot;: &quot;2019-09-16T13:48:04+00:00&quot;
        ///      }
        ///    ]
        ///  }
        ///}.
        /// </summary>
        internal static string CommonResponses_TmSegment {
            get {
                return ResourceManager.GetString("CommonResponses_TmSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;records&quot;: [
        ///    {
        ///      &quot;languageId&quot;: &quot;uk&quot;,
        ///      &quot;text&quot;: &quot;Перекладений текст&quot;
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string CreateTmSegment_Request {
            get {
                return ResourceManager.GetString("CreateTmSegment_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;records&quot;: [
        ///    {
        ///      &quot;languageId&quot;: &quot;uk&quot;,
        ///      &quot;text&quot;: &quot;Перекладений текст&quot;
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string CreateTmSegmentRecords_Request {
            get {
                return ResourceManager.GetString("CreateTmSegmentRecords_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///
        ///    &quot;path&quot;: &quot;/text&quot;,
        ///    &quot;op&quot;: &quot;replace&quot;,
        ///
        ///    &quot;value&quot;: &quot;new name&quot;
        ///  }
        ///].
        /// </summary>
        internal static string EditTmSegmentRecord_Request {
            get {
                return ResourceManager.GetString("EditTmSegmentRecord_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [
        ///    {
        ///      &quot;data&quot;: {
        ///        &quot;id&quot;: 4,
        ///        &quot;records&quot;: [
        ///          {
        ///            &quot;id&quot;: 1,
        ///            &quot;languageId&quot;: &quot;uk&quot;,
        ///            &quot;text&quot;: &quot;Перекладений текст&quot;,
        ///            &quot;usageCount&quot;: 13,
        ///            &quot;createdBy&quot;: 1,
        ///            &quot;updatedBy&quot;: 1,
        ///            &quot;createdAt&quot;: &quot;2019-09-16T13:48:04+00:00&quot;,
        ///            &quot;updatedAt&quot;: &quot;2019-09-16T13:48:04+00:00&quot;
        ///          }
        ///        ]
        ///      }
        ///    }
        ///  ],
        ///  &quot;pagination&quot;: {
        ///    &quot;offset&quot;: 0,
        ///    &quot;limit&quot;: 25
        ///  }
        ///}.
        /// </summary>
        internal static string ListTmSegments_Response {
            get {
                return ResourceManager.GetString("ListTmSegments_Response", resourceCulture);
            }
        }
    }
}
